/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.AdUsers;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdUsersRecord extends UpdatableRecordImpl<AdUsersRecord> implements Record4<Integer, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ad_users.id</code>.
     */
    public AdUsersRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.ad_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ad_users.name</code>.
     */
    public AdUsersRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.ad_users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ad_users.email</code>.
     */
    public AdUsersRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.ad_users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ad_users.created_at</code>.
     */
    public AdUsersRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.ad_users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AdUsers.AD_USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return AdUsers.AD_USERS.NAME;
    }

    @Override
    public Field<String> field3() {
        return AdUsers.AD_USERS.EMAIL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return AdUsers.AD_USERS.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public AdUsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AdUsersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AdUsersRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AdUsersRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AdUsersRecord values(Integer value1, String value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdUsersRecord
     */
    public AdUsersRecord() {
        super(AdUsers.AD_USERS);
    }

    /**
     * Create a detached, initialised AdUsersRecord
     */
    public AdUsersRecord(Integer id, String name, String email, LocalDateTime createdAt) {
        super(AdUsers.AD_USERS);

        setId(id);
        setName(name);
        setEmail(email);
        setCreatedAt(createdAt);
    }

    /**
     * Create a detached, initialised AdUsersRecord
     */
    public AdUsersRecord(com.generated_jooq.tables.pojos.AdUsers value) {
        super(AdUsers.AD_USERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
            setCreatedAt(value.getCreatedAt());
        }
    }
}
