/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.ChCompletions;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChCompletionsRecord extends UpdatableRecordImpl<ChCompletionsRecord> implements Record4<Integer, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ch_completions.id</code>.
     */
    public ChCompletionsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.ch_completions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ch_completions.created_at</code>.
     */
    public ChCompletionsRecord setCreatedAt(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.ch_completions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.ch_completions.request</code>.
     */
    public ChCompletionsRecord setRequest(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.ch_completions.request</code>.
     */
    public String getRequest() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ch_completions.response</code>.
     */
    public ChCompletionsRecord setResponse(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.ch_completions.response</code>.
     */
    public String getResponse() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, LocalDateTime, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, LocalDateTime, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ChCompletions.CH_COMPLETIONS.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ChCompletions.CH_COMPLETIONS.CREATED_AT;
    }

    @Override
    public Field<String> field3() {
        return ChCompletions.CH_COMPLETIONS.REQUEST;
    }

    @Override
    public Field<String> field4() {
        return ChCompletions.CH_COMPLETIONS.RESPONSE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public String component3() {
        return getRequest();
    }

    @Override
    public String component4() {
        return getResponse();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public String value3() {
        return getRequest();
    }

    @Override
    public String value4() {
        return getResponse();
    }

    @Override
    public ChCompletionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ChCompletionsRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ChCompletionsRecord value3(String value) {
        setRequest(value);
        return this;
    }

    @Override
    public ChCompletionsRecord value4(String value) {
        setResponse(value);
        return this;
    }

    @Override
    public ChCompletionsRecord values(Integer value1, LocalDateTime value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChCompletionsRecord
     */
    public ChCompletionsRecord() {
        super(ChCompletions.CH_COMPLETIONS);
    }

    /**
     * Create a detached, initialised ChCompletionsRecord
     */
    public ChCompletionsRecord(Integer id, LocalDateTime createdAt, String request, String response) {
        super(ChCompletions.CH_COMPLETIONS);

        setId(id);
        setCreatedAt(createdAt);
        setRequest(request);
        setResponse(response);
    }

    /**
     * Create a detached, initialised ChCompletionsRecord
     */
    public ChCompletionsRecord(com.generated_jooq.tables.pojos.ChCompletions value) {
        super(ChCompletions.CH_COMPLETIONS);

        if (value != null) {
            setId(value.getId());
            setCreatedAt(value.getCreatedAt());
            setRequest(value.getRequest());
            setResponse(value.getResponse());
        }
    }
}
