/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.MdQuestionTopicElementTemplate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Шаблон за елементи към въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicElementTemplateRecord extends UpdatableRecordImpl<MdQuestionTopicElementTemplateRecord> implements Record5<Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.md_question_topic_element_template.id</code>.
     */
    public MdQuestionTopicElementTemplateRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_element_template.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.md_question_topic_element_template.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public MdQuestionTopicElementTemplateRecord setMdTopicTemplateId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_element_template.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public Integer getMdTopicTemplateId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.md_question_topic_element_template.seq_no</code>.
     * Пореден номер на елемент
     */
    public MdQuestionTopicElementTemplateRecord setSeqNo(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_element_template.seq_no</code>.
     * Пореден номер на елемент
     */
    public Integer getSeqNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.md_question_topic_element_template.name</code>.
     * Наименование на елемент
     */
    public MdQuestionTopicElementTemplateRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_element_template.name</code>.
     * Наименование на елемент
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.md_question_topic_element_template.extraction_question</code>.
     * Въпрос за извличане на отговор
     */
    public MdQuestionTopicElementTemplateRecord setExtractionQuestion(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_element_template.extraction_question</code>.
     * Въпрос за извличане на отговор
     */
    public String getExtractionQuestion() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.MD_TOPIC_TEMPLATE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.SEQ_NO;
    }

    @Override
    public Field<String> field4() {
        return MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.NAME;
    }

    @Override
    public Field<String> field5() {
        return MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.EXTRACTION_QUESTION;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMdTopicTemplateId();
    }

    @Override
    public Integer component3() {
        return getSeqNo();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getExtractionQuestion();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMdTopicTemplateId();
    }

    @Override
    public Integer value3() {
        return getSeqNo();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getExtractionQuestion();
    }

    @Override
    public MdQuestionTopicElementTemplateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MdQuestionTopicElementTemplateRecord value2(Integer value) {
        setMdTopicTemplateId(value);
        return this;
    }

    @Override
    public MdQuestionTopicElementTemplateRecord value3(Integer value) {
        setSeqNo(value);
        return this;
    }

    @Override
    public MdQuestionTopicElementTemplateRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public MdQuestionTopicElementTemplateRecord value5(String value) {
        setExtractionQuestion(value);
        return this;
    }

    @Override
    public MdQuestionTopicElementTemplateRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdQuestionTopicElementTemplateRecord
     */
    public MdQuestionTopicElementTemplateRecord() {
        super(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE);
    }

    /**
     * Create a detached, initialised MdQuestionTopicElementTemplateRecord
     */
    public MdQuestionTopicElementTemplateRecord(Integer id, Integer mdTopicTemplateId, Integer seqNo, String name, String extractionQuestion) {
        super(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE);

        setId(id);
        setMdTopicTemplateId(mdTopicTemplateId);
        setSeqNo(seqNo);
        setName(name);
        setExtractionQuestion(extractionQuestion);
    }

    /**
     * Create a detached, initialised MdQuestionTopicElementTemplateRecord
     */
    public MdQuestionTopicElementTemplateRecord(com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate value) {
        super(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE);

        if (value != null) {
            setId(value.getId());
            setMdTopicTemplateId(value.getMdTopicTemplateId());
            setSeqNo(value.getSeqNo());
            setName(value.getName());
            setExtractionQuestion(value.getExtractionQuestion());
        }
    }
}
