/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.MdQuestionTopicTemplate;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Шаблон за въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicTemplateRecord extends UpdatableRecordImpl<MdQuestionTopicTemplateRecord> implements Record8<Integer, Integer, String, String, String, String, String, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.md_question_topic_template.id</code>.
     */
    public MdQuestionTopicTemplateRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_template.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.md_question_topic_template.seq_no</code>. Пореден
     * номер на темата
     */
    public MdQuestionTopicTemplateRecord setSeqNo(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_template.seq_no</code>. Пореден
     * номер на темата
     */
    public Integer getSeqNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.md_question_topic_template.name</code>.
     * Наименование на темата
     */
    public MdQuestionTopicTemplateRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_template.name</code>.
     * Наименование на темата
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.system_question</code>. Откриващ
     * въпрос от системата
     */
    public MdQuestionTopicTemplateRecord setSystemQuestion(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.system_question</code>. Откриващ
     * въпрос от системата
     */
    public String getSystemQuestion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.md_question_topic_template.system_prompt</code>.
     * Системен промпт въпрос
     */
    public MdQuestionTopicTemplateRecord setSystemPrompt(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_template.system_prompt</code>.
     * Системен промпт въпрос
     */
    public String getSystemPrompt() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.system_check_prompt</code>.
     * Системен промпт за проверка на отговор
     */
    public MdQuestionTopicTemplateRecord setSystemCheckPrompt(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.system_check_prompt</code>.
     * Системен промпт за проверка на отговор
     */
    public String getSystemCheckPrompt() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.confirmation_question</code>.
     * Въпрос за потвърждение от потребителя
     */
    public MdQuestionTopicTemplateRecord setConfirmationQuestion(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.confirmation_question</code>.
     * Въпрос за потвърждение от потребителя
     */
    public String getConfirmationQuestion() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.response_structure</code>.
     * Структура на очаквания отговор
     */
    public MdQuestionTopicTemplateRecord setResponseStructure(JSONB value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.response_structure</code>.
     * Структура на очаквания отговор
     */
    public JSONB getResponseStructure() {
        return (JSONB) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, String, String, String, String, JSONB> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, String, String, String, String, JSONB> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SEQ_NO;
    }

    @Override
    public Field<String> field3() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.NAME;
    }

    @Override
    public Field<String> field4() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_QUESTION;
    }

    @Override
    public Field<String> field5() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_PROMPT;
    }

    @Override
    public Field<String> field6() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_CHECK_PROMPT;
    }

    @Override
    public Field<String> field7() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.CONFIRMATION_QUESTION;
    }

    @Override
    public Field<JSONB> field8() {
        return MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.RESPONSE_STRUCTURE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSeqNo();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getSystemQuestion();
    }

    @Override
    public String component5() {
        return getSystemPrompt();
    }

    @Override
    public String component6() {
        return getSystemCheckPrompt();
    }

    @Override
    public String component7() {
        return getConfirmationQuestion();
    }

    @Override
    public JSONB component8() {
        return getResponseStructure();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSeqNo();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getSystemQuestion();
    }

    @Override
    public String value5() {
        return getSystemPrompt();
    }

    @Override
    public String value6() {
        return getSystemCheckPrompt();
    }

    @Override
    public String value7() {
        return getConfirmationQuestion();
    }

    @Override
    public JSONB value8() {
        return getResponseStructure();
    }

    @Override
    public MdQuestionTopicTemplateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord value2(Integer value) {
        setSeqNo(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord value4(String value) {
        setSystemQuestion(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord value5(String value) {
        setSystemPrompt(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord value6(String value) {
        setSystemCheckPrompt(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord value7(String value) {
        setConfirmationQuestion(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord value8(JSONB value) {
        setResponseStructure(value);
        return this;
    }

    @Override
    public MdQuestionTopicTemplateRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7, JSONB value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdQuestionTopicTemplateRecord
     */
    public MdQuestionTopicTemplateRecord() {
        super(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE);
    }

    /**
     * Create a detached, initialised MdQuestionTopicTemplateRecord
     */
    public MdQuestionTopicTemplateRecord(Integer id, Integer seqNo, String name, String systemQuestion, String systemPrompt, String systemCheckPrompt, String confirmationQuestion, JSONB responseStructure) {
        super(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE);

        setId(id);
        setSeqNo(seqNo);
        setName(name);
        setSystemQuestion(systemQuestion);
        setSystemPrompt(systemPrompt);
        setSystemCheckPrompt(systemCheckPrompt);
        setConfirmationQuestion(confirmationQuestion);
        setResponseStructure(responseStructure);
    }

    /**
     * Create a detached, initialised MdQuestionTopicTemplateRecord
     */
    public MdQuestionTopicTemplateRecord(com.generated_jooq.tables.pojos.MdQuestionTopicTemplate value) {
        super(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE);

        if (value != null) {
            setId(value.getId());
            setSeqNo(value.getSeqNo());
            setName(value.getName());
            setSystemQuestion(value.getSystemQuestion());
            setSystemPrompt(value.getSystemPrompt());
            setSystemCheckPrompt(value.getSystemCheckPrompt());
            setConfirmationQuestion(value.getConfirmationQuestion());
            setResponseStructure(value.getResponseStructure());
        }
    }
}
