/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.OdConversation;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Разговор с потребител
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversationRecord extends UpdatableRecordImpl<OdConversationRecord> implements Record5<Integer, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.od_conversation.id</code>.
     */
    public OdConversationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.od_conversation.od_user_id</code>. Референция към
     * потребителя
     */
    public OdConversationRecord setOdUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.od_user_id</code>. Референция към
     * потребителя
     */
    public Integer getOdUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.od_conversation.name</code>. Наименование на
     * разговора
     */
    public OdConversationRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.name</code>. Наименование на
     * разговора
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.od_conversation.started_at</code>. Начален момент
     * на разговора
     */
    public OdConversationRecord setStartedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.started_at</code>. Начален момент
     * на разговора
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.od_conversation.ended_at</code>. Краен момент на
     * разговора
     */
    public OdConversationRecord setEndedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.ended_at</code>. Краен момент на
     * разговора
     */
    public LocalDateTime getEndedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OdConversation.OD_CONVERSATION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return OdConversation.OD_CONVERSATION.OD_USER_ID;
    }

    @Override
    public Field<String> field3() {
        return OdConversation.OD_CONVERSATION.NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return OdConversation.OD_CONVERSATION.STARTED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return OdConversation.OD_CONVERSATION.ENDED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOdUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public LocalDateTime component4() {
        return getStartedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getEndedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOdUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public LocalDateTime value4() {
        return getStartedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getEndedAt();
    }

    @Override
    public OdConversationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OdConversationRecord value2(Integer value) {
        setOdUserId(value);
        return this;
    }

    @Override
    public OdConversationRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public OdConversationRecord value4(LocalDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public OdConversationRecord value5(LocalDateTime value) {
        setEndedAt(value);
        return this;
    }

    @Override
    public OdConversationRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdConversationRecord
     */
    public OdConversationRecord() {
        super(OdConversation.OD_CONVERSATION);
    }

    /**
     * Create a detached, initialised OdConversationRecord
     */
    public OdConversationRecord(Integer id, Integer odUserId, String name, LocalDateTime startedAt, LocalDateTime endedAt) {
        super(OdConversation.OD_CONVERSATION);

        setId(id);
        setOdUserId(odUserId);
        setName(name);
        setStartedAt(startedAt);
        setEndedAt(endedAt);
    }

    /**
     * Create a detached, initialised OdConversationRecord
     */
    public OdConversationRecord(com.generated_jooq.tables.pojos.OdConversation value) {
        super(OdConversation.OD_CONVERSATION);

        if (value != null) {
            setId(value.getId());
            setOdUserId(value.getOdUserId());
            setName(value.getName());
            setStartedAt(value.getStartedAt());
            setEndedAt(value.getEndedAt());
        }
    }
}
