/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.OdCommunication;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Комуникация по тема в разговор
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdCommunicationRecord extends UpdatableRecordImpl<OdCommunicationRecord> implements Record7<Integer, Integer, LocalDateTime, String, String, Integer, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.od_communication.id</code>.
     */
    public OdCommunicationRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.od_communication.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.od_communication.od_conversation_topic_id</code>.
     * Референция към тема в разговор
     */
    public OdCommunicationRecord setOdConversationTopicId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.od_communication.od_conversation_topic_id</code>.
     * Референция към тема в разговор
     */
    public Integer getOdConversationTopicId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.od_communication.started_at</code>. Начало на
     * комуникацията
     */
    public OdCommunicationRecord setStartedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.od_communication.started_at</code>. Начало на
     * комуникацията
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.od_communication.system_prompt</code>. Системен
     * промпт
     */
    public OdCommunicationRecord setSystemPrompt(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.od_communication.system_prompt</code>. Системен
     * промпт
     */
    public String getSystemPrompt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.od_communication.user_response</code>.
     * Потребителски отговор
     */
    public OdCommunicationRecord setUserResponse(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.od_communication.user_response</code>.
     * Потребителски отговор
     */
    public String getUserResponse() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.od_communication.processing_duration_ms</code>.
     * Продължителност на обработката (ms)
     */
    public OdCommunicationRecord setProcessingDurationMs(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.od_communication.processing_duration_ms</code>.
     * Продължителност на обработката (ms)
     */
    public Integer getProcessingDurationMs() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.od_communication.llm_result</code>. Резултат от
     * LLM обработката
     */
    public OdCommunicationRecord setLlmResult(JSONB value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.od_communication.llm_result</code>. Резултат от
     * LLM обработката
     */
    public JSONB getLlmResult() {
        return (JSONB) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, LocalDateTime, String, String, Integer, JSONB> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, LocalDateTime, String, String, Integer, JSONB> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OdCommunication.OD_COMMUNICATION.ID;
    }

    @Override
    public Field<Integer> field2() {
        return OdCommunication.OD_COMMUNICATION.OD_CONVERSATION_TOPIC_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return OdCommunication.OD_COMMUNICATION.STARTED_AT;
    }

    @Override
    public Field<String> field4() {
        return OdCommunication.OD_COMMUNICATION.SYSTEM_PROMPT;
    }

    @Override
    public Field<String> field5() {
        return OdCommunication.OD_COMMUNICATION.USER_RESPONSE;
    }

    @Override
    public Field<Integer> field6() {
        return OdCommunication.OD_COMMUNICATION.PROCESSING_DURATION_MS;
    }

    @Override
    public Field<JSONB> field7() {
        return OdCommunication.OD_COMMUNICATION.LLM_RESULT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOdConversationTopicId();
    }

    @Override
    public LocalDateTime component3() {
        return getStartedAt();
    }

    @Override
    public String component4() {
        return getSystemPrompt();
    }

    @Override
    public String component5() {
        return getUserResponse();
    }

    @Override
    public Integer component6() {
        return getProcessingDurationMs();
    }

    @Override
    public JSONB component7() {
        return getLlmResult();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOdConversationTopicId();
    }

    @Override
    public LocalDateTime value3() {
        return getStartedAt();
    }

    @Override
    public String value4() {
        return getSystemPrompt();
    }

    @Override
    public String value5() {
        return getUserResponse();
    }

    @Override
    public Integer value6() {
        return getProcessingDurationMs();
    }

    @Override
    public JSONB value7() {
        return getLlmResult();
    }

    @Override
    public OdCommunicationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OdCommunicationRecord value2(Integer value) {
        setOdConversationTopicId(value);
        return this;
    }

    @Override
    public OdCommunicationRecord value3(LocalDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public OdCommunicationRecord value4(String value) {
        setSystemPrompt(value);
        return this;
    }

    @Override
    public OdCommunicationRecord value5(String value) {
        setUserResponse(value);
        return this;
    }

    @Override
    public OdCommunicationRecord value6(Integer value) {
        setProcessingDurationMs(value);
        return this;
    }

    @Override
    public OdCommunicationRecord value7(JSONB value) {
        setLlmResult(value);
        return this;
    }

    @Override
    public OdCommunicationRecord values(Integer value1, Integer value2, LocalDateTime value3, String value4, String value5, Integer value6, JSONB value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdCommunicationRecord
     */
    public OdCommunicationRecord() {
        super(OdCommunication.OD_COMMUNICATION);
    }

    /**
     * Create a detached, initialised OdCommunicationRecord
     */
    public OdCommunicationRecord(Integer id, Integer odConversationTopicId, LocalDateTime startedAt, String systemPrompt, String userResponse, Integer processingDurationMs, JSONB llmResult) {
        super(OdCommunication.OD_COMMUNICATION);

        setId(id);
        setOdConversationTopicId(odConversationTopicId);
        setStartedAt(startedAt);
        setSystemPrompt(systemPrompt);
        setUserResponse(userResponse);
        setProcessingDurationMs(processingDurationMs);
        setLlmResult(llmResult);
    }

    /**
     * Create a detached, initialised OdCommunicationRecord
     */
    public OdCommunicationRecord(com.generated_jooq.tables.pojos.OdCommunication value) {
        super(OdCommunication.OD_COMMUNICATION);

        if (value != null) {
            setId(value.getId());
            setOdConversationTopicId(value.getOdConversationTopicId());
            setStartedAt(value.getStartedAt());
            setSystemPrompt(value.getSystemPrompt());
            setUserResponse(value.getUserResponse());
            setProcessingDurationMs(value.getProcessingDurationMs());
            setLlmResult(value.getLlmResult());
        }
    }
}
