/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.OdConversationTopic;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Теми в разговори
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversationTopicRecord extends UpdatableRecordImpl<OdConversationTopicRecord> implements Record6<Integer, Integer, Integer, String, JSONB, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.od_conversation_topic.id</code>.
     */
    public OdConversationTopicRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.od_conversation_topic.od_conversation_id</code>.
     * Референция към разговор
     */
    public OdConversationTopicRecord setOdConversationId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.od_conversation_id</code>.
     * Референция към разговор
     */
    public Integer getOdConversationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>public.od_conversation_topic.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public OdConversationTopicRecord setMdTopicTemplateId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>public.od_conversation_topic.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public Integer getMdTopicTemplateId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.od_conversation_topic.user_response</code>.
     * Потребителски отговор
     */
    public OdConversationTopicRecord setUserResponse(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.user_response</code>.
     * Потребителски отговор
     */
    public String getUserResponse() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.od_conversation_topic.structured_response</code>.
     * Структуриран отговор
     */
    public OdConversationTopicRecord setStructuredResponse(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.structured_response</code>.
     * Структуриран отговор
     */
    public JSONB getStructuredResponse() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.od_conversation_topic.status</code>. Статус на
     * темата в разговора
     */
    public OdConversationTopicRecord setStatus(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.status</code>. Статус на
     * темата в разговора
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, String, JSONB, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, String, JSONB, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OdConversationTopic.OD_CONVERSATION_TOPIC.ID;
    }

    @Override
    public Field<Integer> field2() {
        return OdConversationTopic.OD_CONVERSATION_TOPIC.OD_CONVERSATION_ID;
    }

    @Override
    public Field<Integer> field3() {
        return OdConversationTopic.OD_CONVERSATION_TOPIC.MD_TOPIC_TEMPLATE_ID;
    }

    @Override
    public Field<String> field4() {
        return OdConversationTopic.OD_CONVERSATION_TOPIC.USER_RESPONSE;
    }

    @Override
    public Field<JSONB> field5() {
        return OdConversationTopic.OD_CONVERSATION_TOPIC.STRUCTURED_RESPONSE;
    }

    @Override
    public Field<String> field6() {
        return OdConversationTopic.OD_CONVERSATION_TOPIC.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOdConversationId();
    }

    @Override
    public Integer component3() {
        return getMdTopicTemplateId();
    }

    @Override
    public String component4() {
        return getUserResponse();
    }

    @Override
    public JSONB component5() {
        return getStructuredResponse();
    }

    @Override
    public String component6() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOdConversationId();
    }

    @Override
    public Integer value3() {
        return getMdTopicTemplateId();
    }

    @Override
    public String value4() {
        return getUserResponse();
    }

    @Override
    public JSONB value5() {
        return getStructuredResponse();
    }

    @Override
    public String value6() {
        return getStatus();
    }

    @Override
    public OdConversationTopicRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OdConversationTopicRecord value2(Integer value) {
        setOdConversationId(value);
        return this;
    }

    @Override
    public OdConversationTopicRecord value3(Integer value) {
        setMdTopicTemplateId(value);
        return this;
    }

    @Override
    public OdConversationTopicRecord value4(String value) {
        setUserResponse(value);
        return this;
    }

    @Override
    public OdConversationTopicRecord value5(JSONB value) {
        setStructuredResponse(value);
        return this;
    }

    @Override
    public OdConversationTopicRecord value6(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public OdConversationTopicRecord values(Integer value1, Integer value2, Integer value3, String value4, JSONB value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdConversationTopicRecord
     */
    public OdConversationTopicRecord() {
        super(OdConversationTopic.OD_CONVERSATION_TOPIC);
    }

    /**
     * Create a detached, initialised OdConversationTopicRecord
     */
    public OdConversationTopicRecord(Integer id, Integer odConversationId, Integer mdTopicTemplateId, String userResponse, JSONB structuredResponse, String status) {
        super(OdConversationTopic.OD_CONVERSATION_TOPIC);

        setId(id);
        setOdConversationId(odConversationId);
        setMdTopicTemplateId(mdTopicTemplateId);
        setUserResponse(userResponse);
        setStructuredResponse(structuredResponse);
        setStatus(status);
    }

    /**
     * Create a detached, initialised OdConversationTopicRecord
     */
    public OdConversationTopicRecord(com.generated_jooq.tables.pojos.OdConversationTopic value) {
        super(OdConversationTopic.OD_CONVERSATION_TOPIC);

        if (value != null) {
            setId(value.getId());
            setOdConversationId(value.getOdConversationId());
            setMdTopicTemplateId(value.getMdTopicTemplateId());
            setUserResponse(value.getUserResponse());
            setStructuredResponse(value.getStructuredResponse());
            setStatus(value.getStatus());
        }
    }
}
