/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.records;


import com.generated_jooq.tables.OdUser;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Потребител в системата
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdUserRecord extends UpdatableRecordImpl<OdUserRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.od_user.id</code>.
     */
    public OdUserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.od_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.od_user.name</code>. Име на потребителя
     */
    public OdUserRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.od_user.name</code>. Име на потребителя
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.od_user.email</code>. Имейл адрес
     */
    public OdUserRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.od_user.email</code>. Имейл адрес
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.od_user.secret_key</code>. Секретен ключ за
     * идентификация
     */
    public OdUserRecord setSecretKey(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.od_user.secret_key</code>. Секретен ключ за
     * идентификация
     */
    public String getSecretKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.od_user.remaining_requests</code>. Оставащи
     * заявки за потребителя
     */
    public OdUserRecord setRemainingRequests(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.od_user.remaining_requests</code>. Оставащи
     * заявки за потребителя
     */
    public Integer getRemainingRequests() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OdUser.OD_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return OdUser.OD_USER.NAME;
    }

    @Override
    public Field<String> field3() {
        return OdUser.OD_USER.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return OdUser.OD_USER.SECRET_KEY;
    }

    @Override
    public Field<Integer> field5() {
        return OdUser.OD_USER.REMAINING_REQUESTS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getSecretKey();
    }

    @Override
    public Integer component5() {
        return getRemainingRequests();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getSecretKey();
    }

    @Override
    public Integer value5() {
        return getRemainingRequests();
    }

    @Override
    public OdUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OdUserRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public OdUserRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public OdUserRecord value4(String value) {
        setSecretKey(value);
        return this;
    }

    @Override
    public OdUserRecord value5(Integer value) {
        setRemainingRequests(value);
        return this;
    }

    @Override
    public OdUserRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdUserRecord
     */
    public OdUserRecord() {
        super(OdUser.OD_USER);
    }

    /**
     * Create a detached, initialised OdUserRecord
     */
    public OdUserRecord(Integer id, String name, String email, String secretKey, Integer remainingRequests) {
        super(OdUser.OD_USER);

        setId(id);
        setName(name);
        setEmail(email);
        setSecretKey(secretKey);
        setRemainingRequests(remainingRequests);
    }

    /**
     * Create a detached, initialised OdUserRecord
     */
    public OdUserRecord(com.generated_jooq.tables.pojos.OdUser value) {
        super(OdUser.OD_USER);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
            setSecretKey(value.getSecretKey());
            setRemainingRequests(value.getRemainingRequests());
        }
    }
}
