/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String email;
    private LocalDateTime createdAt;

    public AdUsers() {}

    public AdUsers(AdUsers value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
        this.createdAt = value.createdAt;
    }

    public AdUsers(
        Integer id,
        String name,
        String email,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.ad_users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ad_users.id</code>.
     */
    public AdUsers setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.ad_users.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.ad_users.name</code>.
     */
    public AdUsers setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.ad_users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.ad_users.email</code>.
     */
    public AdUsers setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.ad_users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.ad_users.created_at</code>.
     */
    public AdUsers setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AdUsers other = (AdUsers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AdUsers (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
