/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChCompletions implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private LocalDateTime createdAt;
    private String request;
    private String response;

    public ChCompletions() {}

    public ChCompletions(ChCompletions value) {
        this.id = value.id;
        this.createdAt = value.createdAt;
        this.request = value.request;
        this.response = value.response;
    }

    public ChCompletions(
        Integer id,
        LocalDateTime createdAt,
        String request,
        String response
    ) {
        this.id = id;
        this.createdAt = createdAt;
        this.request = request;
        this.response = response;
    }

    /**
     * Getter for <code>public.ch_completions.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ch_completions.id</code>.
     */
    public ChCompletions setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.ch_completions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.ch_completions.created_at</code>.
     */
    public ChCompletions setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.ch_completions.request</code>.
     */
    public String getRequest() {
        return this.request;
    }

    /**
     * Setter for <code>public.ch_completions.request</code>.
     */
    public ChCompletions setRequest(String request) {
        this.request = request;
        return this;
    }

    /**
     * Getter for <code>public.ch_completions.response</code>.
     */
    public String getResponse() {
        return this.response;
    }

    /**
     * Setter for <code>public.ch_completions.response</code>.
     */
    public ChCompletions setResponse(String response) {
        this.response = response;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChCompletions other = (ChCompletions) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.request == null) {
            if (other.request != null)
                return false;
        }
        else if (!this.request.equals(other.request))
            return false;
        if (this.response == null) {
            if (other.response != null)
                return false;
        }
        else if (!this.response.equals(other.response))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.request == null) ? 0 : this.request.hashCode());
        result = prime * result + ((this.response == null) ? 0 : this.response.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChCompletions (");

        sb.append(id);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(request);
        sb.append(", ").append(response);

        sb.append(")");
        return sb.toString();
    }
}
