/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * Шаблон за въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicTemplate implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer seqNo;
    private String name;
    private String systemQuestion;
    private String systemPrompt;
    private String systemCheckPrompt;
    private String confirmationQuestion;
    private JSONB responseStructure;

    public MdQuestionTopicTemplate() {}

    public MdQuestionTopicTemplate(MdQuestionTopicTemplate value) {
        this.id = value.id;
        this.seqNo = value.seqNo;
        this.name = value.name;
        this.systemQuestion = value.systemQuestion;
        this.systemPrompt = value.systemPrompt;
        this.systemCheckPrompt = value.systemCheckPrompt;
        this.confirmationQuestion = value.confirmationQuestion;
        this.responseStructure = value.responseStructure;
    }

    public MdQuestionTopicTemplate(
        Integer id,
        Integer seqNo,
        String name,
        String systemQuestion,
        String systemPrompt,
        String systemCheckPrompt,
        String confirmationQuestion,
        JSONB responseStructure
    ) {
        this.id = id;
        this.seqNo = seqNo;
        this.name = name;
        this.systemQuestion = systemQuestion;
        this.systemPrompt = systemPrompt;
        this.systemCheckPrompt = systemCheckPrompt;
        this.confirmationQuestion = confirmationQuestion;
        this.responseStructure = responseStructure;
    }

    /**
     * Getter for <code>public.md_question_topic_template.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.md_question_topic_template.id</code>.
     */
    public MdQuestionTopicTemplate setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_template.seq_no</code>. Пореден
     * номер на темата
     */
    public Integer getSeqNo() {
        return this.seqNo;
    }

    /**
     * Setter for <code>public.md_question_topic_template.seq_no</code>. Пореден
     * номер на темата
     */
    public MdQuestionTopicTemplate setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_template.name</code>.
     * Наименование на темата
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.md_question_topic_template.name</code>.
     * Наименование на темата
     */
    public MdQuestionTopicTemplate setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.system_question</code>. Откриващ
     * въпрос от системата
     */
    public String getSystemQuestion() {
        return this.systemQuestion;
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.system_question</code>. Откриващ
     * въпрос от системата
     */
    public MdQuestionTopicTemplate setSystemQuestion(String systemQuestion) {
        this.systemQuestion = systemQuestion;
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_template.system_prompt</code>.
     * Системен промпт въпрос
     */
    public String getSystemPrompt() {
        return this.systemPrompt;
    }

    /**
     * Setter for <code>public.md_question_topic_template.system_prompt</code>.
     * Системен промпт въпрос
     */
    public MdQuestionTopicTemplate setSystemPrompt(String systemPrompt) {
        this.systemPrompt = systemPrompt;
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.system_check_prompt</code>.
     * Системен промпт за проверка на отговор
     */
    public String getSystemCheckPrompt() {
        return this.systemCheckPrompt;
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.system_check_prompt</code>.
     * Системен промпт за проверка на отговор
     */
    public MdQuestionTopicTemplate setSystemCheckPrompt(String systemCheckPrompt) {
        this.systemCheckPrompt = systemCheckPrompt;
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.confirmation_question</code>.
     * Въпрос за потвърждение от потребителя
     */
    public String getConfirmationQuestion() {
        return this.confirmationQuestion;
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.confirmation_question</code>.
     * Въпрос за потвърждение от потребителя
     */
    public MdQuestionTopicTemplate setConfirmationQuestion(String confirmationQuestion) {
        this.confirmationQuestion = confirmationQuestion;
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_template.response_structure</code>.
     * Структура на очаквания отговор
     */
    public JSONB getResponseStructure() {
        return this.responseStructure;
    }

    /**
     * Setter for
     * <code>public.md_question_topic_template.response_structure</code>.
     * Структура на очаквания отговор
     */
    public MdQuestionTopicTemplate setResponseStructure(JSONB responseStructure) {
        this.responseStructure = responseStructure;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MdQuestionTopicTemplate other = (MdQuestionTopicTemplate) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.seqNo == null) {
            if (other.seqNo != null)
                return false;
        }
        else if (!this.seqNo.equals(other.seqNo))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.systemQuestion == null) {
            if (other.systemQuestion != null)
                return false;
        }
        else if (!this.systemQuestion.equals(other.systemQuestion))
            return false;
        if (this.systemPrompt == null) {
            if (other.systemPrompt != null)
                return false;
        }
        else if (!this.systemPrompt.equals(other.systemPrompt))
            return false;
        if (this.systemCheckPrompt == null) {
            if (other.systemCheckPrompt != null)
                return false;
        }
        else if (!this.systemCheckPrompt.equals(other.systemCheckPrompt))
            return false;
        if (this.confirmationQuestion == null) {
            if (other.confirmationQuestion != null)
                return false;
        }
        else if (!this.confirmationQuestion.equals(other.confirmationQuestion))
            return false;
        if (this.responseStructure == null) {
            if (other.responseStructure != null)
                return false;
        }
        else if (!this.responseStructure.equals(other.responseStructure))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.seqNo == null) ? 0 : this.seqNo.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.systemQuestion == null) ? 0 : this.systemQuestion.hashCode());
        result = prime * result + ((this.systemPrompt == null) ? 0 : this.systemPrompt.hashCode());
        result = prime * result + ((this.systemCheckPrompt == null) ? 0 : this.systemCheckPrompt.hashCode());
        result = prime * result + ((this.confirmationQuestion == null) ? 0 : this.confirmationQuestion.hashCode());
        result = prime * result + ((this.responseStructure == null) ? 0 : this.responseStructure.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MdQuestionTopicTemplate (");

        sb.append(id);
        sb.append(", ").append(seqNo);
        sb.append(", ").append(name);
        sb.append(", ").append(systemQuestion);
        sb.append(", ").append(systemPrompt);
        sb.append(", ").append(systemCheckPrompt);
        sb.append(", ").append(confirmationQuestion);
        sb.append(", ").append(responseStructure);

        sb.append(")");
        return sb.toString();
    }
}
