/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;


/**
 * Шаблон за елементи към въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicElementTemplate implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer mdTopicTemplateId;
    private Integer seqNo;
    private String name;
    private String extractionQuestion;

    public MdQuestionTopicElementTemplate() {}

    public MdQuestionTopicElementTemplate(MdQuestionTopicElementTemplate value) {
        this.id = value.id;
        this.mdTopicTemplateId = value.mdTopicTemplateId;
        this.seqNo = value.seqNo;
        this.name = value.name;
        this.extractionQuestion = value.extractionQuestion;
    }

    public MdQuestionTopicElementTemplate(
        Integer id,
        Integer mdTopicTemplateId,
        Integer seqNo,
        String name,
        String extractionQuestion
    ) {
        this.id = id;
        this.mdTopicTemplateId = mdTopicTemplateId;
        this.seqNo = seqNo;
        this.name = name;
        this.extractionQuestion = extractionQuestion;
    }

    /**
     * Getter for <code>public.md_question_topic_element_template.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.md_question_topic_element_template.id</code>.
     */
    public MdQuestionTopicElementTemplate setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_element_template.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public Integer getMdTopicTemplateId() {
        return this.mdTopicTemplateId;
    }

    /**
     * Setter for
     * <code>public.md_question_topic_element_template.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public MdQuestionTopicElementTemplate setMdTopicTemplateId(Integer mdTopicTemplateId) {
        this.mdTopicTemplateId = mdTopicTemplateId;
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_element_template.seq_no</code>.
     * Пореден номер на елемент
     */
    public Integer getSeqNo() {
        return this.seqNo;
    }

    /**
     * Setter for <code>public.md_question_topic_element_template.seq_no</code>.
     * Пореден номер на елемент
     */
    public MdQuestionTopicElementTemplate setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
        return this;
    }

    /**
     * Getter for <code>public.md_question_topic_element_template.name</code>.
     * Наименование на елемент
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.md_question_topic_element_template.name</code>.
     * Наименование на елемент
     */
    public MdQuestionTopicElementTemplate setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for
     * <code>public.md_question_topic_element_template.extraction_question</code>.
     * Въпрос за извличане на отговор
     */
    public String getExtractionQuestion() {
        return this.extractionQuestion;
    }

    /**
     * Setter for
     * <code>public.md_question_topic_element_template.extraction_question</code>.
     * Въпрос за извличане на отговор
     */
    public MdQuestionTopicElementTemplate setExtractionQuestion(String extractionQuestion) {
        this.extractionQuestion = extractionQuestion;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MdQuestionTopicElementTemplate other = (MdQuestionTopicElementTemplate) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.mdTopicTemplateId == null) {
            if (other.mdTopicTemplateId != null)
                return false;
        }
        else if (!this.mdTopicTemplateId.equals(other.mdTopicTemplateId))
            return false;
        if (this.seqNo == null) {
            if (other.seqNo != null)
                return false;
        }
        else if (!this.seqNo.equals(other.seqNo))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.extractionQuestion == null) {
            if (other.extractionQuestion != null)
                return false;
        }
        else if (!this.extractionQuestion.equals(other.extractionQuestion))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.mdTopicTemplateId == null) ? 0 : this.mdTopicTemplateId.hashCode());
        result = prime * result + ((this.seqNo == null) ? 0 : this.seqNo.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.extractionQuestion == null) ? 0 : this.extractionQuestion.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MdQuestionTopicElementTemplate (");

        sb.append(id);
        sb.append(", ").append(mdTopicTemplateId);
        sb.append(", ").append(seqNo);
        sb.append(", ").append(name);
        sb.append(", ").append(extractionQuestion);

        sb.append(")");
        return sb.toString();
    }
}
