/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * Разговор с потребител
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversation implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer odUserId;
    private String name;
    private LocalDateTime startedAt;
    private LocalDateTime endedAt;

    public OdConversation() {}

    public OdConversation(OdConversation value) {
        this.id = value.id;
        this.odUserId = value.odUserId;
        this.name = value.name;
        this.startedAt = value.startedAt;
        this.endedAt = value.endedAt;
    }

    public OdConversation(
        Integer id,
        Integer odUserId,
        String name,
        LocalDateTime startedAt,
        LocalDateTime endedAt
    ) {
        this.id = id;
        this.odUserId = odUserId;
        this.name = name;
        this.startedAt = startedAt;
        this.endedAt = endedAt;
    }

    /**
     * Getter for <code>public.od_conversation.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.od_conversation.id</code>.
     */
    public OdConversation setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.od_user_id</code>. Референция към
     * потребителя
     */
    public Integer getOdUserId() {
        return this.odUserId;
    }

    /**
     * Setter for <code>public.od_conversation.od_user_id</code>. Референция към
     * потребителя
     */
    public OdConversation setOdUserId(Integer odUserId) {
        this.odUserId = odUserId;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.name</code>. Наименование на
     * разговора
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.od_conversation.name</code>. Наименование на
     * разговора
     */
    public OdConversation setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.started_at</code>. Начален момент
     * на разговора
     */
    public LocalDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.od_conversation.started_at</code>. Начален момент
     * на разговора
     */
    public OdConversation setStartedAt(LocalDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation.ended_at</code>. Краен момент на
     * разговора
     */
    public LocalDateTime getEndedAt() {
        return this.endedAt;
    }

    /**
     * Setter for <code>public.od_conversation.ended_at</code>. Краен момент на
     * разговора
     */
    public OdConversation setEndedAt(LocalDateTime endedAt) {
        this.endedAt = endedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OdConversation other = (OdConversation) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.odUserId == null) {
            if (other.odUserId != null)
                return false;
        }
        else if (!this.odUserId.equals(other.odUserId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.startedAt == null) {
            if (other.startedAt != null)
                return false;
        }
        else if (!this.startedAt.equals(other.startedAt))
            return false;
        if (this.endedAt == null) {
            if (other.endedAt != null)
                return false;
        }
        else if (!this.endedAt.equals(other.endedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.odUserId == null) ? 0 : this.odUserId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.startedAt == null) ? 0 : this.startedAt.hashCode());
        result = prime * result + ((this.endedAt == null) ? 0 : this.endedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OdConversation (");

        sb.append(id);
        sb.append(", ").append(odUserId);
        sb.append(", ").append(name);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(endedAt);

        sb.append(")");
        return sb.toString();
    }
}
