/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSONB;


/**
 * Комуникация по тема в разговор
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdCommunication implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer odConversationTopicId;
    private LocalDateTime startedAt;
    private String systemPrompt;
    private String userResponse;
    private Integer processingDurationMs;
    private JSONB llmResult;

    public OdCommunication() {}

    public OdCommunication(OdCommunication value) {
        this.id = value.id;
        this.odConversationTopicId = value.odConversationTopicId;
        this.startedAt = value.startedAt;
        this.systemPrompt = value.systemPrompt;
        this.userResponse = value.userResponse;
        this.processingDurationMs = value.processingDurationMs;
        this.llmResult = value.llmResult;
    }

    public OdCommunication(
        Integer id,
        Integer odConversationTopicId,
        LocalDateTime startedAt,
        String systemPrompt,
        String userResponse,
        Integer processingDurationMs,
        JSONB llmResult
    ) {
        this.id = id;
        this.odConversationTopicId = odConversationTopicId;
        this.startedAt = startedAt;
        this.systemPrompt = systemPrompt;
        this.userResponse = userResponse;
        this.processingDurationMs = processingDurationMs;
        this.llmResult = llmResult;
    }

    /**
     * Getter for <code>public.od_communication.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.od_communication.id</code>.
     */
    public OdCommunication setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.od_communication.od_conversation_topic_id</code>.
     * Референция към тема в разговор
     */
    public Integer getOdConversationTopicId() {
        return this.odConversationTopicId;
    }

    /**
     * Setter for <code>public.od_communication.od_conversation_topic_id</code>.
     * Референция към тема в разговор
     */
    public OdCommunication setOdConversationTopicId(Integer odConversationTopicId) {
        this.odConversationTopicId = odConversationTopicId;
        return this;
    }

    /**
     * Getter for <code>public.od_communication.started_at</code>. Начало на
     * комуникацията
     */
    public LocalDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.od_communication.started_at</code>. Начало на
     * комуникацията
     */
    public OdCommunication setStartedAt(LocalDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.od_communication.system_prompt</code>. Системен
     * промпт
     */
    public String getSystemPrompt() {
        return this.systemPrompt;
    }

    /**
     * Setter for <code>public.od_communication.system_prompt</code>. Системен
     * промпт
     */
    public OdCommunication setSystemPrompt(String systemPrompt) {
        this.systemPrompt = systemPrompt;
        return this;
    }

    /**
     * Getter for <code>public.od_communication.user_response</code>.
     * Потребителски отговор
     */
    public String getUserResponse() {
        return this.userResponse;
    }

    /**
     * Setter for <code>public.od_communication.user_response</code>.
     * Потребителски отговор
     */
    public OdCommunication setUserResponse(String userResponse) {
        this.userResponse = userResponse;
        return this;
    }

    /**
     * Getter for <code>public.od_communication.processing_duration_ms</code>.
     * Продължителност на обработката (ms)
     */
    public Integer getProcessingDurationMs() {
        return this.processingDurationMs;
    }

    /**
     * Setter for <code>public.od_communication.processing_duration_ms</code>.
     * Продължителност на обработката (ms)
     */
    public OdCommunication setProcessingDurationMs(Integer processingDurationMs) {
        this.processingDurationMs = processingDurationMs;
        return this;
    }

    /**
     * Getter for <code>public.od_communication.llm_result</code>. Резултат от
     * LLM обработката
     */
    public JSONB getLlmResult() {
        return this.llmResult;
    }

    /**
     * Setter for <code>public.od_communication.llm_result</code>. Резултат от
     * LLM обработката
     */
    public OdCommunication setLlmResult(JSONB llmResult) {
        this.llmResult = llmResult;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OdCommunication other = (OdCommunication) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.odConversationTopicId == null) {
            if (other.odConversationTopicId != null)
                return false;
        }
        else if (!this.odConversationTopicId.equals(other.odConversationTopicId))
            return false;
        if (this.startedAt == null) {
            if (other.startedAt != null)
                return false;
        }
        else if (!this.startedAt.equals(other.startedAt))
            return false;
        if (this.systemPrompt == null) {
            if (other.systemPrompt != null)
                return false;
        }
        else if (!this.systemPrompt.equals(other.systemPrompt))
            return false;
        if (this.userResponse == null) {
            if (other.userResponse != null)
                return false;
        }
        else if (!this.userResponse.equals(other.userResponse))
            return false;
        if (this.processingDurationMs == null) {
            if (other.processingDurationMs != null)
                return false;
        }
        else if (!this.processingDurationMs.equals(other.processingDurationMs))
            return false;
        if (this.llmResult == null) {
            if (other.llmResult != null)
                return false;
        }
        else if (!this.llmResult.equals(other.llmResult))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.odConversationTopicId == null) ? 0 : this.odConversationTopicId.hashCode());
        result = prime * result + ((this.startedAt == null) ? 0 : this.startedAt.hashCode());
        result = prime * result + ((this.systemPrompt == null) ? 0 : this.systemPrompt.hashCode());
        result = prime * result + ((this.userResponse == null) ? 0 : this.userResponse.hashCode());
        result = prime * result + ((this.processingDurationMs == null) ? 0 : this.processingDurationMs.hashCode());
        result = prime * result + ((this.llmResult == null) ? 0 : this.llmResult.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OdCommunication (");

        sb.append(id);
        sb.append(", ").append(odConversationTopicId);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(systemPrompt);
        sb.append(", ").append(userResponse);
        sb.append(", ").append(processingDurationMs);
        sb.append(", ").append(llmResult);

        sb.append(")");
        return sb.toString();
    }
}
