/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * Теми в разговори
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversationTopic implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer odConversationId;
    private Integer mdTopicTemplateId;
    private String userResponse;
    private JSONB structuredResponse;
    private String status;

    public OdConversationTopic() {}

    public OdConversationTopic(OdConversationTopic value) {
        this.id = value.id;
        this.odConversationId = value.odConversationId;
        this.mdTopicTemplateId = value.mdTopicTemplateId;
        this.userResponse = value.userResponse;
        this.structuredResponse = value.structuredResponse;
        this.status = value.status;
    }

    public OdConversationTopic(
        Integer id,
        Integer odConversationId,
        Integer mdTopicTemplateId,
        String userResponse,
        JSONB structuredResponse,
        String status
    ) {
        this.id = id;
        this.odConversationId = odConversationId;
        this.mdTopicTemplateId = mdTopicTemplateId;
        this.userResponse = userResponse;
        this.structuredResponse = structuredResponse;
        this.status = status;
    }

    /**
     * Getter for <code>public.od_conversation_topic.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.od_conversation_topic.id</code>.
     */
    public OdConversationTopic setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.od_conversation_id</code>.
     * Референция към разговор
     */
    public Integer getOdConversationId() {
        return this.odConversationId;
    }

    /**
     * Setter for <code>public.od_conversation_topic.od_conversation_id</code>.
     * Референция към разговор
     */
    public OdConversationTopic setOdConversationId(Integer odConversationId) {
        this.odConversationId = odConversationId;
        return this;
    }

    /**
     * Getter for
     * <code>public.od_conversation_topic.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public Integer getMdTopicTemplateId() {
        return this.mdTopicTemplateId;
    }

    /**
     * Setter for
     * <code>public.od_conversation_topic.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public OdConversationTopic setMdTopicTemplateId(Integer mdTopicTemplateId) {
        this.mdTopicTemplateId = mdTopicTemplateId;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.user_response</code>.
     * Потребителски отговор
     */
    public String getUserResponse() {
        return this.userResponse;
    }

    /**
     * Setter for <code>public.od_conversation_topic.user_response</code>.
     * Потребителски отговор
     */
    public OdConversationTopic setUserResponse(String userResponse) {
        this.userResponse = userResponse;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.structured_response</code>.
     * Структуриран отговор
     */
    public JSONB getStructuredResponse() {
        return this.structuredResponse;
    }

    /**
     * Setter for <code>public.od_conversation_topic.structured_response</code>.
     * Структуриран отговор
     */
    public OdConversationTopic setStructuredResponse(JSONB structuredResponse) {
        this.structuredResponse = structuredResponse;
        return this;
    }

    /**
     * Getter for <code>public.od_conversation_topic.status</code>. Статус на
     * темата в разговора
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.od_conversation_topic.status</code>. Статус на
     * темата в разговора
     */
    public OdConversationTopic setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OdConversationTopic other = (OdConversationTopic) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.odConversationId == null) {
            if (other.odConversationId != null)
                return false;
        }
        else if (!this.odConversationId.equals(other.odConversationId))
            return false;
        if (this.mdTopicTemplateId == null) {
            if (other.mdTopicTemplateId != null)
                return false;
        }
        else if (!this.mdTopicTemplateId.equals(other.mdTopicTemplateId))
            return false;
        if (this.userResponse == null) {
            if (other.userResponse != null)
                return false;
        }
        else if (!this.userResponse.equals(other.userResponse))
            return false;
        if (this.structuredResponse == null) {
            if (other.structuredResponse != null)
                return false;
        }
        else if (!this.structuredResponse.equals(other.structuredResponse))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.odConversationId == null) ? 0 : this.odConversationId.hashCode());
        result = prime * result + ((this.mdTopicTemplateId == null) ? 0 : this.mdTopicTemplateId.hashCode());
        result = prime * result + ((this.userResponse == null) ? 0 : this.userResponse.hashCode());
        result = prime * result + ((this.structuredResponse == null) ? 0 : this.structuredResponse.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OdConversationTopic (");

        sb.append(id);
        sb.append(", ").append(odConversationId);
        sb.append(", ").append(mdTopicTemplateId);
        sb.append(", ").append(userResponse);
        sb.append(", ").append(structuredResponse);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
