/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.pojos;


import java.io.Serializable;


/**
 * Потребител в системата
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String email;
    private String secretKey;
    private Integer remainingRequests;

    public OdUser() {}

    public OdUser(OdUser value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
        this.secretKey = value.secretKey;
        this.remainingRequests = value.remainingRequests;
    }

    public OdUser(
        Integer id,
        String name,
        String email,
        String secretKey,
        Integer remainingRequests
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.secretKey = secretKey;
        this.remainingRequests = remainingRequests;
    }

    /**
     * Getter for <code>public.od_user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.od_user.id</code>.
     */
    public OdUser setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.od_user.name</code>. Име на потребителя
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.od_user.name</code>. Име на потребителя
     */
    public OdUser setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.od_user.email</code>. Имейл адрес
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.od_user.email</code>. Имейл адрес
     */
    public OdUser setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.od_user.secret_key</code>. Секретен ключ за
     * идентификация
     */
    public String getSecretKey() {
        return this.secretKey;
    }

    /**
     * Setter for <code>public.od_user.secret_key</code>. Секретен ключ за
     * идентификация
     */
    public OdUser setSecretKey(String secretKey) {
        this.secretKey = secretKey;
        return this;
    }

    /**
     * Getter for <code>public.od_user.remaining_requests</code>. Оставащи
     * заявки за потребителя
     */
    public Integer getRemainingRequests() {
        return this.remainingRequests;
    }

    /**
     * Setter for <code>public.od_user.remaining_requests</code>. Оставащи
     * заявки за потребителя
     */
    public OdUser setRemainingRequests(Integer remainingRequests) {
        this.remainingRequests = remainingRequests;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OdUser other = (OdUser) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.secretKey == null) {
            if (other.secretKey != null)
                return false;
        }
        else if (!this.secretKey.equals(other.secretKey))
            return false;
        if (this.remainingRequests == null) {
            if (other.remainingRequests != null)
                return false;
        }
        else if (!this.remainingRequests.equals(other.remainingRequests))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.secretKey == null) ? 0 : this.secretKey.hashCode());
        result = prime * result + ((this.remainingRequests == null) ? 0 : this.remainingRequests.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OdUser (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(secretKey);
        sb.append(", ").append(remainingRequests);

        sb.append(")");
        return sb.toString();
    }
}
