/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.routines;


import com.generated_jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChCompletionInsert extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.ch_completion_insert.p_request</code>.
     */
    public static final Parameter<String> P_REQUEST = Internal.createParameter("p_request", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.ch_completion_insert.p_response</code>.
     */
    public static final Parameter<String> P_RESPONSE = Internal.createParameter("p_response", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public ChCompletionInsert() {
        super("ch_completion_insert", Public.PUBLIC);

        addInParameter(P_REQUEST);
        addInParameter(P_RESPONSE);
        setSQLUsable(false);
    }

    /**
     * Set the <code>p_request</code> parameter IN value to the routine
     */
    public void setPRequest(String value) {
        setValue(P_REQUEST, value);
    }

    /**
     * Set the <code>p_response</code> parameter IN value to the routine
     */
    public void setPResponse(String value) {
        setValue(P_RESPONSE, value);
    }
}
