/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.routines;


import com.generated_jooq.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getsystemmessage extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.getsystemmessage.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.getsystemmessage.secret_key</code>.
     */
    public static final Parameter<String> SECRET_KEY = Internal.createParameter("secret_key", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public Getsystemmessage() {
        super("getsystemmessage", Public.PUBLIC, SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(SECRET_KEY);
    }

    /**
     * Set the <code>secret_key</code> parameter IN value to the routine
     */
    public void setSecretKey(String value) {
        setValue(SECRET_KEY, value);
    }

    /**
     * Set the <code>secret_key</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public Getsystemmessage setSecretKey(Field<String> field) {
        setField(SECRET_KEY, field);
        return this;
    }
}
