/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.routines;


import com.generated_jooq.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InsertUser extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.insert_user.p_name</code>.
     */
    public static final Parameter<String> P_NAME = Internal.createParameter("p_name", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.insert_user.p_email</code>.
     */
    public static final Parameter<String> P_EMAIL = Internal.createParameter("p_email", SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public InsertUser() {
        super("insert_user", Public.PUBLIC);

        addInParameter(P_NAME);
        addInParameter(P_EMAIL);
        setSQLUsable(false);
    }

    /**
     * Set the <code>p_name</code> parameter IN value to the routine
     */
    public void setPName(String value) {
        setValue(P_NAME, value);
    }

    /**
     * Set the <code>p_email</code> parameter IN value to the routine
     */
    public void setPEmail(String value) {
        setValue(P_EMAIL, value);
    }
}
