/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.AdUsersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdUsers extends TableImpl<AdUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ad_users</code>
     */
    public static final AdUsers AD_USERS = new AdUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdUsersRecord> getRecordType() {
        return AdUsersRecord.class;
    }

    /**
     * The column <code>public.ad_users.id</code>.
     */
    public final TableField<AdUsersRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ad_users.name</code>.
     */
    public final TableField<AdUsersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.ad_users.email</code>.
     */
    public final TableField<AdUsersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.ad_users.created_at</code>.
     */
    public final TableField<AdUsersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private AdUsers(Name alias, Table<AdUsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private AdUsers(Name alias, Table<AdUsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ad_users</code> table reference
     */
    public AdUsers(String alias) {
        this(DSL.name(alias), AD_USERS);
    }

    /**
     * Create an aliased <code>public.ad_users</code> table reference
     */
    public AdUsers(Name alias) {
        this(alias, AD_USERS);
    }

    /**
     * Create a <code>public.ad_users</code> table reference
     */
    public AdUsers() {
        this(DSL.name("ad_users"), null);
    }

    public <O extends Record> AdUsers(Table<O> child, ForeignKey<O, AdUsersRecord> key) {
        super(child, key, AD_USERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AdUsersRecord, Integer> getIdentity() {
        return (Identity<AdUsersRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AdUsersRecord> getPrimaryKey() {
        return Keys.AD_USERS_PKEY;
    }

    @Override
    public List<UniqueKey<AdUsersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AD_USERS_EMAIL_KEY);
    }

    @Override
    public AdUsers as(String alias) {
        return new AdUsers(DSL.name(alias), this);
    }

    @Override
    public AdUsers as(Name alias) {
        return new AdUsers(alias, this);
    }

    @Override
    public AdUsers as(Table<?> alias) {
        return new AdUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdUsers rename(String name) {
        return new AdUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdUsers rename(Name name) {
        return new AdUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdUsers rename(Table<?> name) {
        return new AdUsers(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super String, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
