/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.ChCompletionsRecord;

import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChCompletions extends TableImpl<ChCompletionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ch_completions</code>
     */
    public static final ChCompletions CH_COMPLETIONS = new ChCompletions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChCompletionsRecord> getRecordType() {
        return ChCompletionsRecord.class;
    }

    /**
     * The column <code>public.ch_completions.id</code>.
     */
    public final TableField<ChCompletionsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ch_completions.created_at</code>.
     */
    public final TableField<ChCompletionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.ch_completions.request</code>.
     */
    public final TableField<ChCompletionsRecord, String> REQUEST = createField(DSL.name("request"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.ch_completions.response</code>.
     */
    public final TableField<ChCompletionsRecord, String> RESPONSE = createField(DSL.name("response"), SQLDataType.CLOB, this, "");

    private ChCompletions(Name alias, Table<ChCompletionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChCompletions(Name alias, Table<ChCompletionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ch_completions</code> table reference
     */
    public ChCompletions(String alias) {
        this(DSL.name(alias), CH_COMPLETIONS);
    }

    /**
     * Create an aliased <code>public.ch_completions</code> table reference
     */
    public ChCompletions(Name alias) {
        this(alias, CH_COMPLETIONS);
    }

    /**
     * Create a <code>public.ch_completions</code> table reference
     */
    public ChCompletions() {
        this(DSL.name("ch_completions"), null);
    }

    public <O extends Record> ChCompletions(Table<O> child, ForeignKey<O, ChCompletionsRecord> key) {
        super(child, key, CH_COMPLETIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ChCompletionsRecord, Integer> getIdentity() {
        return (Identity<ChCompletionsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ChCompletionsRecord> getPrimaryKey() {
        return Keys.CH_COMPLETIONS_PKEY;
    }

    @Override
    public ChCompletions as(String alias) {
        return new ChCompletions(DSL.name(alias), this);
    }

    @Override
    public ChCompletions as(Name alias) {
        return new ChCompletions(alias, this);
    }

    @Override
    public ChCompletions as(Table<?> alias) {
        return new ChCompletions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChCompletions rename(String name) {
        return new ChCompletions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChCompletions rename(Name name) {
        return new ChCompletions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChCompletions rename(Table<?> name) {
        return new ChCompletions(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, LocalDateTime, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super LocalDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super LocalDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
