/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Indexes;
import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.MdQuestionTopicTemplateRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Шаблон за въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicTemplate extends TableImpl<MdQuestionTopicTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.md_question_topic_template</code>
     */
    public static final MdQuestionTopicTemplate MD_QUESTION_TOPIC_TEMPLATE = new MdQuestionTopicTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MdQuestionTopicTemplateRecord> getRecordType() {
        return MdQuestionTopicTemplateRecord.class;
    }

    /**
     * The column <code>public.md_question_topic_template.id</code>.
     */
    public final TableField<MdQuestionTopicTemplateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.md_question_topic_template.seq_no</code>. Пореден
     * номер на темата
     */
    public final TableField<MdQuestionTopicTemplateRecord, Integer> SEQ_NO = createField(DSL.name("seq_no"), SQLDataType.INTEGER.nullable(false), this, "Пореден номер на темата");

    /**
     * The column <code>public.md_question_topic_template.name</code>.
     * Наименование на темата
     */
    public final TableField<MdQuestionTopicTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Наименование на темата");

    /**
     * The column
     * <code>public.md_question_topic_template.system_question</code>. Откриващ
     * въпрос от системата
     */
    public final TableField<MdQuestionTopicTemplateRecord, String> SYSTEM_QUESTION = createField(DSL.name("system_question"), SQLDataType.CLOB.nullable(false), this, "Откриващ въпрос от системата");

    /**
     * The column <code>public.md_question_topic_template.system_prompt</code>.
     * Системен промпт въпрос
     */
    public final TableField<MdQuestionTopicTemplateRecord, String> SYSTEM_PROMPT = createField(DSL.name("system_prompt"), SQLDataType.CLOB, this, "Системен промпт въпрос");

    /**
     * The column
     * <code>public.md_question_topic_template.system_check_prompt</code>.
     * Системен промпт за проверка на отговор
     */
    public final TableField<MdQuestionTopicTemplateRecord, String> SYSTEM_CHECK_PROMPT = createField(DSL.name("system_check_prompt"), SQLDataType.CLOB, this, "Системен промпт за проверка на отговор");

    /**
     * The column
     * <code>public.md_question_topic_template.confirmation_question</code>.
     * Въпрос за потвърждение от потребителя
     */
    public final TableField<MdQuestionTopicTemplateRecord, String> CONFIRMATION_QUESTION = createField(DSL.name("confirmation_question"), SQLDataType.CLOB, this, "Въпрос за потвърждение от потребителя");

    /**
     * The column
     * <code>public.md_question_topic_template.response_structure</code>.
     * Структура на очаквания отговор
     */
    public final TableField<MdQuestionTopicTemplateRecord, JSONB> RESPONSE_STRUCTURE = createField(DSL.name("response_structure"), SQLDataType.JSONB, this, "Структура на очаквания отговор");

    private MdQuestionTopicTemplate(Name alias, Table<MdQuestionTopicTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private MdQuestionTopicTemplate(Name alias, Table<MdQuestionTopicTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Шаблон за въпросна тема"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.md_question_topic_template</code> table
     * reference
     */
    public MdQuestionTopicTemplate(String alias) {
        this(DSL.name(alias), MD_QUESTION_TOPIC_TEMPLATE);
    }

    /**
     * Create an aliased <code>public.md_question_topic_template</code> table
     * reference
     */
    public MdQuestionTopicTemplate(Name alias) {
        this(alias, MD_QUESTION_TOPIC_TEMPLATE);
    }

    /**
     * Create a <code>public.md_question_topic_template</code> table reference
     */
    public MdQuestionTopicTemplate() {
        this(DSL.name("md_question_topic_template"), null);
    }

    public <O extends Record> MdQuestionTopicTemplate(Table<O> child, ForeignKey<O, MdQuestionTopicTemplateRecord> key) {
        super(child, key, MD_QUESTION_TOPIC_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UQ_MD_QUESTION_TOPIC_TEMPLATE_NAME);
    }

    @Override
    public Identity<MdQuestionTopicTemplateRecord, Integer> getIdentity() {
        return (Identity<MdQuestionTopicTemplateRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MdQuestionTopicTemplateRecord> getPrimaryKey() {
        return Keys.MD_QUESTION_TOPIC_TEMPLATE_PKEY;
    }

    @Override
    public MdQuestionTopicTemplate as(String alias) {
        return new MdQuestionTopicTemplate(DSL.name(alias), this);
    }

    @Override
    public MdQuestionTopicTemplate as(Name alias) {
        return new MdQuestionTopicTemplate(alias, this);
    }

    @Override
    public MdQuestionTopicTemplate as(Table<?> alias) {
        return new MdQuestionTopicTemplate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MdQuestionTopicTemplate rename(String name) {
        return new MdQuestionTopicTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MdQuestionTopicTemplate rename(Name name) {
        return new MdQuestionTopicTemplate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MdQuestionTopicTemplate rename(Table<?> name) {
        return new MdQuestionTopicTemplate(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, String, String, String, String, JSONB> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super JSONB, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Integer, ? super Integer, ? super String, ? super String, ? super String, ? super String, ? super String, ? super JSONB, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
