/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Indexes;
import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.MdQuestionTopicElementTemplateRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Шаблон за елементи към въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicElementTemplate extends TableImpl<MdQuestionTopicElementTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.md_question_topic_element_template</code>
     */
    public static final MdQuestionTopicElementTemplate MD_QUESTION_TOPIC_ELEMENT_TEMPLATE = new MdQuestionTopicElementTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MdQuestionTopicElementTemplateRecord> getRecordType() {
        return MdQuestionTopicElementTemplateRecord.class;
    }

    /**
     * The column <code>public.md_question_topic_element_template.id</code>.
     */
    public final TableField<MdQuestionTopicElementTemplateRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.md_question_topic_element_template.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public final TableField<MdQuestionTopicElementTemplateRecord, Integer> MD_TOPIC_TEMPLATE_ID = createField(DSL.name("md_topic_template_id"), SQLDataType.INTEGER.nullable(false), this, "Референция към шаблон на тема");

    /**
     * The column <code>public.md_question_topic_element_template.seq_no</code>.
     * Пореден номер на елемент
     */
    public final TableField<MdQuestionTopicElementTemplateRecord, Integer> SEQ_NO = createField(DSL.name("seq_no"), SQLDataType.INTEGER.nullable(false), this, "Пореден номер на елемент");

    /**
     * The column <code>public.md_question_topic_element_template.name</code>.
     * Наименование на елемент
     */
    public final TableField<MdQuestionTopicElementTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Наименование на елемент");

    /**
     * The column
     * <code>public.md_question_topic_element_template.extraction_question</code>.
     * Въпрос за извличане на отговор
     */
    public final TableField<MdQuestionTopicElementTemplateRecord, String> EXTRACTION_QUESTION = createField(DSL.name("extraction_question"), SQLDataType.CLOB.nullable(false), this, "Въпрос за извличане на отговор");

    private MdQuestionTopicElementTemplate(Name alias, Table<MdQuestionTopicElementTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private MdQuestionTopicElementTemplate(Name alias, Table<MdQuestionTopicElementTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Шаблон за елементи към въпросна тема"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.md_question_topic_element_template</code>
     * table reference
     */
    public MdQuestionTopicElementTemplate(String alias) {
        this(DSL.name(alias), MD_QUESTION_TOPIC_ELEMENT_TEMPLATE);
    }

    /**
     * Create an aliased <code>public.md_question_topic_element_template</code>
     * table reference
     */
    public MdQuestionTopicElementTemplate(Name alias) {
        this(alias, MD_QUESTION_TOPIC_ELEMENT_TEMPLATE);
    }

    /**
     * Create a <code>public.md_question_topic_element_template</code> table
     * reference
     */
    public MdQuestionTopicElementTemplate() {
        this(DSL.name("md_question_topic_element_template"), null);
    }

    public <O extends Record> MdQuestionTopicElementTemplate(Table<O> child, ForeignKey<O, MdQuestionTopicElementTemplateRecord> key) {
        super(child, key, MD_QUESTION_TOPIC_ELEMENT_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_MD_QTE_TEMPLATE_ID);
    }

    @Override
    public Identity<MdQuestionTopicElementTemplateRecord, Integer> getIdentity() {
        return (Identity<MdQuestionTopicElementTemplateRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<MdQuestionTopicElementTemplateRecord> getPrimaryKey() {
        return Keys.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE_PKEY;
    }

    @Override
    public List<ForeignKey<MdQuestionTopicElementTemplateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE__MD_QUESTION_TOPIC_ELEMENT_TEMPLATE_MD_TOPIC_TEMPLATE_ID_FKEY);
    }

    private transient MdQuestionTopicTemplate _mdQuestionTopicTemplate;

    /**
     * Get the implicit join path to the
     * <code>public.md_question_topic_template</code> table.
     */
    public MdQuestionTopicTemplate mdQuestionTopicTemplate() {
        if (_mdQuestionTopicTemplate == null)
            _mdQuestionTopicTemplate = new MdQuestionTopicTemplate(this, Keys.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE__MD_QUESTION_TOPIC_ELEMENT_TEMPLATE_MD_TOPIC_TEMPLATE_ID_FKEY);

        return _mdQuestionTopicTemplate;
    }

    @Override
    public MdQuestionTopicElementTemplate as(String alias) {
        return new MdQuestionTopicElementTemplate(DSL.name(alias), this);
    }

    @Override
    public MdQuestionTopicElementTemplate as(Name alias) {
        return new MdQuestionTopicElementTemplate(alias, this);
    }

    @Override
    public MdQuestionTopicElementTemplate as(Table<?> alias) {
        return new MdQuestionTopicElementTemplate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MdQuestionTopicElementTemplate rename(String name) {
        return new MdQuestionTopicElementTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MdQuestionTopicElementTemplate rename(Name name) {
        return new MdQuestionTopicElementTemplate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MdQuestionTopicElementTemplate rename(Table<?> name) {
        return new MdQuestionTopicElementTemplate(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super Integer, ? super Integer, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super Integer, ? super Integer, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
