/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Indexes;
import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.OdCommunicationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Комуникация по тема в разговор
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdCommunication extends TableImpl<OdCommunicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.od_communication</code>
     */
    public static final OdCommunication OD_COMMUNICATION = new OdCommunication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdCommunicationRecord> getRecordType() {
        return OdCommunicationRecord.class;
    }

    /**
     * The column <code>public.od_communication.id</code>.
     */
    public final TableField<OdCommunicationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.od_communication.od_conversation_topic_id</code>.
     * Референция към тема в разговор
     */
    public final TableField<OdCommunicationRecord, Integer> OD_CONVERSATION_TOPIC_ID = createField(DSL.name("od_conversation_topic_id"), SQLDataType.INTEGER.nullable(false), this, "Референция към тема в разговор");

    /**
     * The column <code>public.od_communication.started_at</code>. Начало на
     * комуникацията
     */
    public final TableField<OdCommunicationRecord, LocalDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "Начало на комуникацията");

    /**
     * The column <code>public.od_communication.system_prompt</code>. Системен
     * промпт
     */
    public final TableField<OdCommunicationRecord, String> SYSTEM_PROMPT = createField(DSL.name("system_prompt"), SQLDataType.CLOB.nullable(false), this, "Системен промпт");

    /**
     * The column <code>public.od_communication.user_response</code>.
     * Потребителски отговор
     */
    public final TableField<OdCommunicationRecord, String> USER_RESPONSE = createField(DSL.name("user_response"), SQLDataType.CLOB, this, "Потребителски отговор");

    /**
     * The column <code>public.od_communication.processing_duration_ms</code>.
     * Продължителност на обработката (ms)
     */
    public final TableField<OdCommunicationRecord, Integer> PROCESSING_DURATION_MS = createField(DSL.name("processing_duration_ms"), SQLDataType.INTEGER, this, "Продължителност на обработката (ms)");

    /**
     * The column <code>public.od_communication.llm_result</code>. Резултат от
     * LLM обработката
     */
    public final TableField<OdCommunicationRecord, JSONB> LLM_RESULT = createField(DSL.name("llm_result"), SQLDataType.JSONB, this, "Резултат от LLM обработката");

    private OdCommunication(Name alias, Table<OdCommunicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdCommunication(Name alias, Table<OdCommunicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Комуникация по тема в разговор"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.od_communication</code> table reference
     */
    public OdCommunication(String alias) {
        this(DSL.name(alias), OD_COMMUNICATION);
    }

    /**
     * Create an aliased <code>public.od_communication</code> table reference
     */
    public OdCommunication(Name alias) {
        this(alias, OD_COMMUNICATION);
    }

    /**
     * Create a <code>public.od_communication</code> table reference
     */
    public OdCommunication() {
        this(DSL.name("od_communication"), null);
    }

    public <O extends Record> OdCommunication(Table<O> child, ForeignKey<O, OdCommunicationRecord> key) {
        super(child, key, OD_COMMUNICATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OD_COMMUNICATION_TOPIC_ID);
    }

    @Override
    public Identity<OdCommunicationRecord, Integer> getIdentity() {
        return (Identity<OdCommunicationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OdCommunicationRecord> getPrimaryKey() {
        return Keys.OD_COMMUNICATION_PKEY;
    }

    @Override
    public List<ForeignKey<OdCommunicationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OD_COMMUNICATION__OD_COMMUNICATION_OD_CONVERSATION_TOPIC_ID_FKEY);
    }

    private transient OdConversationTopic _odConversationTopic;

    /**
     * Get the implicit join path to the
     * <code>public.od_conversation_topic</code> table.
     */
    public OdConversationTopic odConversationTopic() {
        if (_odConversationTopic == null)
            _odConversationTopic = new OdConversationTopic(this, Keys.OD_COMMUNICATION__OD_COMMUNICATION_OD_CONVERSATION_TOPIC_ID_FKEY);

        return _odConversationTopic;
    }

    @Override
    public OdCommunication as(String alias) {
        return new OdCommunication(DSL.name(alias), this);
    }

    @Override
    public OdCommunication as(Name alias) {
        return new OdCommunication(alias, this);
    }

    @Override
    public OdCommunication as(Table<?> alias) {
        return new OdCommunication(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdCommunication rename(String name) {
        return new OdCommunication(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdCommunication rename(Name name) {
        return new OdCommunication(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdCommunication rename(Table<?> name) {
        return new OdCommunication(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, LocalDateTime, String, String, Integer, JSONB> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Integer, ? super Integer, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? super JSONB, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Integer, ? super Integer, ? super LocalDateTime, ? super String, ? super String, ? super Integer, ? super JSONB, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
