/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Indexes;
import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.OdConversationTopicRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Теми в разговори
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversationTopic extends TableImpl<OdConversationTopicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.od_conversation_topic</code>
     */
    public static final OdConversationTopic OD_CONVERSATION_TOPIC = new OdConversationTopic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdConversationTopicRecord> getRecordType() {
        return OdConversationTopicRecord.class;
    }

    /**
     * The column <code>public.od_conversation_topic.id</code>.
     */
    public final TableField<OdConversationTopicRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.od_conversation_topic.od_conversation_id</code>.
     * Референция към разговор
     */
    public final TableField<OdConversationTopicRecord, Integer> OD_CONVERSATION_ID = createField(DSL.name("od_conversation_id"), SQLDataType.INTEGER.nullable(false), this, "Референция към разговор");

    /**
     * The column
     * <code>public.od_conversation_topic.md_topic_template_id</code>.
     * Референция към шаблон на тема
     */
    public final TableField<OdConversationTopicRecord, Integer> MD_TOPIC_TEMPLATE_ID = createField(DSL.name("md_topic_template_id"), SQLDataType.INTEGER.nullable(false), this, "Референция към шаблон на тема");

    /**
     * The column <code>public.od_conversation_topic.user_response</code>.
     * Потребителски отговор
     */
    public final TableField<OdConversationTopicRecord, String> USER_RESPONSE = createField(DSL.name("user_response"), SQLDataType.CLOB, this, "Потребителски отговор");

    /**
     * The column <code>public.od_conversation_topic.structured_response</code>.
     * Структуриран отговор
     */
    public final TableField<OdConversationTopicRecord, JSONB> STRUCTURED_RESPONSE = createField(DSL.name("structured_response"), SQLDataType.JSONB, this, "Структуриран отговор");

    /**
     * The column <code>public.od_conversation_topic.status</code>. Статус на
     * темата в разговора
     */
    public final TableField<OdConversationTopicRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("'new'::text"), SQLDataType.CLOB)), this, "Статус на темата в разговора");

    private OdConversationTopic(Name alias, Table<OdConversationTopicRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdConversationTopic(Name alias, Table<OdConversationTopicRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Теми в разговори"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.od_conversation_topic</code> table
     * reference
     */
    public OdConversationTopic(String alias) {
        this(DSL.name(alias), OD_CONVERSATION_TOPIC);
    }

    /**
     * Create an aliased <code>public.od_conversation_topic</code> table
     * reference
     */
    public OdConversationTopic(Name alias) {
        this(alias, OD_CONVERSATION_TOPIC);
    }

    /**
     * Create a <code>public.od_conversation_topic</code> table reference
     */
    public OdConversationTopic() {
        this(DSL.name("od_conversation_topic"), null);
    }

    public <O extends Record> OdConversationTopic(Table<O> child, ForeignKey<O, OdConversationTopicRecord> key) {
        super(child, key, OD_CONVERSATION_TOPIC);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OD_CONV_TOPIC_CONV_ID);
    }

    @Override
    public Identity<OdConversationTopicRecord, Integer> getIdentity() {
        return (Identity<OdConversationTopicRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OdConversationTopicRecord> getPrimaryKey() {
        return Keys.OD_CONVERSATION_TOPIC_PKEY;
    }

    @Override
    public List<ForeignKey<OdConversationTopicRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OD_CONVERSATION_TOPIC__OD_CONVERSATION_TOPIC_OD_CONVERSATION_ID_FKEY, Keys.OD_CONVERSATION_TOPIC__OD_CONVERSATION_TOPIC_MD_TOPIC_TEMPLATE_ID_FKEY);
    }

    private transient OdConversation _odConversation;
    private transient MdQuestionTopicTemplate _mdQuestionTopicTemplate;

    /**
     * Get the implicit join path to the <code>public.od_conversation</code>
     * table.
     */
    public OdConversation odConversation() {
        if (_odConversation == null)
            _odConversation = new OdConversation(this, Keys.OD_CONVERSATION_TOPIC__OD_CONVERSATION_TOPIC_OD_CONVERSATION_ID_FKEY);

        return _odConversation;
    }

    /**
     * Get the implicit join path to the
     * <code>public.md_question_topic_template</code> table.
     */
    public MdQuestionTopicTemplate mdQuestionTopicTemplate() {
        if (_mdQuestionTopicTemplate == null)
            _mdQuestionTopicTemplate = new MdQuestionTopicTemplate(this, Keys.OD_CONVERSATION_TOPIC__OD_CONVERSATION_TOPIC_MD_TOPIC_TEMPLATE_ID_FKEY);

        return _mdQuestionTopicTemplate;
    }

    @Override
    public List<Check<OdConversationTopicRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("od_conversation_topic_status_check"), "((status = ANY (ARRAY['new'::text, 'open'::text, 'closed'::text])))", true)
        );
    }

    @Override
    public OdConversationTopic as(String alias) {
        return new OdConversationTopic(DSL.name(alias), this);
    }

    @Override
    public OdConversationTopic as(Name alias) {
        return new OdConversationTopic(alias, this);
    }

    @Override
    public OdConversationTopic as(Table<?> alias) {
        return new OdConversationTopic(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdConversationTopic rename(String name) {
        return new OdConversationTopic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdConversationTopic rename(Name name) {
        return new OdConversationTopic(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdConversationTopic rename(Table<?> name) {
        return new OdConversationTopic(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, String, JSONB, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super Integer, ? super Integer, ? super String, ? super JSONB, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super Integer, ? super Integer, ? super String, ? super JSONB, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
