/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Indexes;
import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.OdConversationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Разговор с потребител
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversation extends TableImpl<OdConversationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.od_conversation</code>
     */
    public static final OdConversation OD_CONVERSATION = new OdConversation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdConversationRecord> getRecordType() {
        return OdConversationRecord.class;
    }

    /**
     * The column <code>public.od_conversation.id</code>.
     */
    public final TableField<OdConversationRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.od_conversation.od_user_id</code>. Референция към
     * потребителя
     */
    public final TableField<OdConversationRecord, Integer> OD_USER_ID = createField(DSL.name("od_user_id"), SQLDataType.INTEGER.nullable(false), this, "Референция към потребителя");

    /**
     * The column <code>public.od_conversation.name</code>. Наименование на
     * разговора
     */
    public final TableField<OdConversationRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "Наименование на разговора");

    /**
     * The column <code>public.od_conversation.started_at</code>. Начален момент
     * на разговора
     */
    public final TableField<OdConversationRecord, LocalDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "Начален момент на разговора");

    /**
     * The column <code>public.od_conversation.ended_at</code>. Краен момент на
     * разговора
     */
    public final TableField<OdConversationRecord, LocalDateTime> ENDED_AT = createField(DSL.name("ended_at"), SQLDataType.LOCALDATETIME(6), this, "Краен момент на разговора");

    private OdConversation(Name alias, Table<OdConversationRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdConversation(Name alias, Table<OdConversationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Разговор с потребител"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.od_conversation</code> table reference
     */
    public OdConversation(String alias) {
        this(DSL.name(alias), OD_CONVERSATION);
    }

    /**
     * Create an aliased <code>public.od_conversation</code> table reference
     */
    public OdConversation(Name alias) {
        this(alias, OD_CONVERSATION);
    }

    /**
     * Create a <code>public.od_conversation</code> table reference
     */
    public OdConversation() {
        this(DSL.name("od_conversation"), null);
    }

    public <O extends Record> OdConversation(Table<O> child, ForeignKey<O, OdConversationRecord> key) {
        super(child, key, OD_CONVERSATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OD_CONVERSATION_USER_ID);
    }

    @Override
    public Identity<OdConversationRecord, Integer> getIdentity() {
        return (Identity<OdConversationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OdConversationRecord> getPrimaryKey() {
        return Keys.OD_CONVERSATION_PKEY;
    }

    @Override
    public List<ForeignKey<OdConversationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OD_CONVERSATION__OD_CONVERSATION_OD_USER_ID_FKEY);
    }

    private transient OdUser _odUser;

    /**
     * Get the implicit join path to the <code>public.od_user</code> table.
     */
    public OdUser odUser() {
        if (_odUser == null)
            _odUser = new OdUser(this, Keys.OD_CONVERSATION__OD_CONVERSATION_OD_USER_ID_FKEY);

        return _odUser;
    }

    @Override
    public OdConversation as(String alias) {
        return new OdConversation(DSL.name(alias), this);
    }

    @Override
    public OdConversation as(Name alias) {
        return new OdConversation(alias, this);
    }

    @Override
    public OdConversation as(Table<?> alias) {
        return new OdConversation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdConversation rename(String name) {
        return new OdConversation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdConversation rename(Name name) {
        return new OdConversation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdConversation rename(Table<?> name) {
        return new OdConversation(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
