/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables;


import com.generated_jooq.Keys;
import com.generated_jooq.Public;
import com.generated_jooq.tables.records.OdUserRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Потребител в системата
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdUser extends TableImpl<OdUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.od_user</code>
     */
    public static final OdUser OD_USER = new OdUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdUserRecord> getRecordType() {
        return OdUserRecord.class;
    }

    /**
     * The column <code>public.od_user.id</code>.
     */
    public final TableField<OdUserRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.od_user.name</code>. Име на потребителя
     */
    public final TableField<OdUserRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "Име на потребителя");

    /**
     * The column <code>public.od_user.email</code>. Имейл адрес
     */
    public final TableField<OdUserRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.CLOB.nullable(false), this, "Имейл адрес");

    /**
     * The column <code>public.od_user.secret_key</code>. Секретен ключ за
     * идентификация
     */
    public final TableField<OdUserRecord, String> SECRET_KEY = createField(DSL.name("secret_key"), SQLDataType.CLOB.nullable(false), this, "Секретен ключ за идентификация");

    /**
     * The column <code>public.od_user.remaining_requests</code>. Оставащи
     * заявки за потребителя
     */
    public final TableField<OdUserRecord, Integer> REMAINING_REQUESTS = createField(DSL.name("remaining_requests"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("10"), SQLDataType.INTEGER)), this, "Оставащи заявки за потребителя");

    private OdUser(Name alias, Table<OdUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdUser(Name alias, Table<OdUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Потребител в системата"), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.od_user</code> table reference
     */
    public OdUser(String alias) {
        this(DSL.name(alias), OD_USER);
    }

    /**
     * Create an aliased <code>public.od_user</code> table reference
     */
    public OdUser(Name alias) {
        this(alias, OD_USER);
    }

    /**
     * Create a <code>public.od_user</code> table reference
     */
    public OdUser() {
        this(DSL.name("od_user"), null);
    }

    public <O extends Record> OdUser(Table<O> child, ForeignKey<O, OdUserRecord> key) {
        super(child, key, OD_USER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OdUserRecord, Integer> getIdentity() {
        return (Identity<OdUserRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OdUserRecord> getPrimaryKey() {
        return Keys.OD_USER_PKEY;
    }

    @Override
    public List<UniqueKey<OdUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.OD_USER_EMAIL_KEY);
    }

    @Override
    public OdUser as(String alias) {
        return new OdUser(DSL.name(alias), this);
    }

    @Override
    public OdUser as(Name alias) {
        return new OdUser(alias, this);
    }

    @Override
    public OdUser as(Table<?> alias) {
        return new OdUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdUser rename(String name) {
        return new OdUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdUser rename(Name name) {
        return new OdUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdUser rename(Table<?> name) {
        return new OdUser(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super String, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super String, ? super String, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
