/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq;


import com.generated_jooq.tables.MdQuestionTopicElementTemplate;
import com.generated_jooq.tables.MdQuestionTopicTemplate;
import com.generated_jooq.tables.OdCommunication;
import com.generated_jooq.tables.OdConversation;
import com.generated_jooq.tables.OdConversationTopic;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_MD_QTE_TEMPLATE_ID = Internal.createIndex(DSL.name("idx_md_qte_template_id"), MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE, new OrderField[] { MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.MD_TOPIC_TEMPLATE_ID }, false);
    public static final Index IDX_OD_COMMUNICATION_TOPIC_ID = Internal.createIndex(DSL.name("idx_od_communication_topic_id"), OdCommunication.OD_COMMUNICATION, new OrderField[] { OdCommunication.OD_COMMUNICATION.OD_CONVERSATION_TOPIC_ID }, false);
    public static final Index IDX_OD_CONV_TOPIC_CONV_ID = Internal.createIndex(DSL.name("idx_od_conv_topic_conv_id"), OdConversationTopic.OD_CONVERSATION_TOPIC, new OrderField[] { OdConversationTopic.OD_CONVERSATION_TOPIC.OD_CONVERSATION_ID }, false);
    public static final Index IDX_OD_CONVERSATION_USER_ID = Internal.createIndex(DSL.name("idx_od_conversation_user_id"), OdConversation.OD_CONVERSATION, new OrderField[] { OdConversation.OD_CONVERSATION.OD_USER_ID }, false);
    public static final Index UQ_MD_QUESTION_TOPIC_TEMPLATE_NAME = Internal.createIndex(DSL.name("uq_md_question_topic_template_name"), MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE, new OrderField[] { MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.NAME }, true);
}
