/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq;


import com.generated_jooq.tables.AdUsers;
import com.generated_jooq.tables.ChCompletions;
import com.generated_jooq.tables.MdQuestionTopicElementTemplate;
import com.generated_jooq.tables.MdQuestionTopicTemplate;
import com.generated_jooq.tables.OdCommunication;
import com.generated_jooq.tables.OdConversation;
import com.generated_jooq.tables.OdConversationTopic;
import com.generated_jooq.tables.OdUser;
import com.generated_jooq.tables.records.AdUsersRecord;
import com.generated_jooq.tables.records.ChCompletionsRecord;
import com.generated_jooq.tables.records.MdQuestionTopicElementTemplateRecord;
import com.generated_jooq.tables.records.MdQuestionTopicTemplateRecord;
import com.generated_jooq.tables.records.OdCommunicationRecord;
import com.generated_jooq.tables.records.OdConversationRecord;
import com.generated_jooq.tables.records.OdConversationTopicRecord;
import com.generated_jooq.tables.records.OdUserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdUsersRecord> AD_USERS_EMAIL_KEY = Internal.createUniqueKey(AdUsers.AD_USERS, DSL.name("ad_users_email_key"), new TableField[] { AdUsers.AD_USERS.EMAIL }, true);
    public static final UniqueKey<AdUsersRecord> AD_USERS_PKEY = Internal.createUniqueKey(AdUsers.AD_USERS, DSL.name("ad_users_pkey"), new TableField[] { AdUsers.AD_USERS.ID }, true);
    public static final UniqueKey<ChCompletionsRecord> CH_COMPLETIONS_PKEY = Internal.createUniqueKey(ChCompletions.CH_COMPLETIONS, DSL.name("ch_completions_pkey"), new TableField[] { ChCompletions.CH_COMPLETIONS.ID }, true);
    public static final UniqueKey<MdQuestionTopicElementTemplateRecord> MD_QUESTION_TOPIC_ELEMENT_TEMPLATE_PKEY = Internal.createUniqueKey(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE, DSL.name("md_question_topic_element_template_pkey"), new TableField[] { MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.ID }, true);
    public static final UniqueKey<MdQuestionTopicTemplateRecord> MD_QUESTION_TOPIC_TEMPLATE_PKEY = Internal.createUniqueKey(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE, DSL.name("md_question_topic_template_pkey"), new TableField[] { MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID }, true);
    public static final UniqueKey<OdCommunicationRecord> OD_COMMUNICATION_PKEY = Internal.createUniqueKey(OdCommunication.OD_COMMUNICATION, DSL.name("od_communication_pkey"), new TableField[] { OdCommunication.OD_COMMUNICATION.ID }, true);
    public static final UniqueKey<OdConversationRecord> OD_CONVERSATION_PKEY = Internal.createUniqueKey(OdConversation.OD_CONVERSATION, DSL.name("od_conversation_pkey"), new TableField[] { OdConversation.OD_CONVERSATION.ID }, true);
    public static final UniqueKey<OdConversationTopicRecord> OD_CONVERSATION_TOPIC_PKEY = Internal.createUniqueKey(OdConversationTopic.OD_CONVERSATION_TOPIC, DSL.name("od_conversation_topic_pkey"), new TableField[] { OdConversationTopic.OD_CONVERSATION_TOPIC.ID }, true);
    public static final UniqueKey<OdUserRecord> OD_USER_EMAIL_KEY = Internal.createUniqueKey(OdUser.OD_USER, DSL.name("od_user_email_key"), new TableField[] { OdUser.OD_USER.EMAIL }, true);
    public static final UniqueKey<OdUserRecord> OD_USER_PKEY = Internal.createUniqueKey(OdUser.OD_USER, DSL.name("od_user_pkey"), new TableField[] { OdUser.OD_USER.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MdQuestionTopicElementTemplateRecord, MdQuestionTopicTemplateRecord> MD_QUESTION_TOPIC_ELEMENT_TEMPLATE__MD_QUESTION_TOPIC_ELEMENT_TEMPLATE_MD_TOPIC_TEMPLATE_ID_FKEY = Internal.createForeignKey(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE, DSL.name("md_question_topic_element_template_md_topic_template_id_fkey"), new TableField[] { MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.MD_TOPIC_TEMPLATE_ID }, Keys.MD_QUESTION_TOPIC_TEMPLATE_PKEY, new TableField[] { MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID }, true);
    public static final ForeignKey<OdCommunicationRecord, OdConversationTopicRecord> OD_COMMUNICATION__OD_COMMUNICATION_OD_CONVERSATION_TOPIC_ID_FKEY = Internal.createForeignKey(OdCommunication.OD_COMMUNICATION, DSL.name("od_communication_od_conversation_topic_id_fkey"), new TableField[] { OdCommunication.OD_COMMUNICATION.OD_CONVERSATION_TOPIC_ID }, Keys.OD_CONVERSATION_TOPIC_PKEY, new TableField[] { OdConversationTopic.OD_CONVERSATION_TOPIC.ID }, true);
    public static final ForeignKey<OdConversationRecord, OdUserRecord> OD_CONVERSATION__OD_CONVERSATION_OD_USER_ID_FKEY = Internal.createForeignKey(OdConversation.OD_CONVERSATION, DSL.name("od_conversation_od_user_id_fkey"), new TableField[] { OdConversation.OD_CONVERSATION.OD_USER_ID }, Keys.OD_USER_PKEY, new TableField[] { OdUser.OD_USER.ID }, true);
    public static final ForeignKey<OdConversationTopicRecord, MdQuestionTopicTemplateRecord> OD_CONVERSATION_TOPIC__OD_CONVERSATION_TOPIC_MD_TOPIC_TEMPLATE_ID_FKEY = Internal.createForeignKey(OdConversationTopic.OD_CONVERSATION_TOPIC, DSL.name("od_conversation_topic_md_topic_template_id_fkey"), new TableField[] { OdConversationTopic.OD_CONVERSATION_TOPIC.MD_TOPIC_TEMPLATE_ID }, Keys.MD_QUESTION_TOPIC_TEMPLATE_PKEY, new TableField[] { MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID }, true);
    public static final ForeignKey<OdConversationTopicRecord, OdConversationRecord> OD_CONVERSATION_TOPIC__OD_CONVERSATION_TOPIC_OD_CONVERSATION_ID_FKEY = Internal.createForeignKey(OdConversationTopic.OD_CONVERSATION_TOPIC, DSL.name("od_conversation_topic_od_conversation_id_fkey"), new TableField[] { OdConversationTopic.OD_CONVERSATION_TOPIC.OD_CONVERSATION_ID }, Keys.OD_CONVERSATION_PKEY, new TableField[] { OdConversation.OD_CONVERSATION.ID }, true);
}
