/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq;


import com.generated_jooq.tables.AdUsers;
import com.generated_jooq.tables.ChCompletions;
import com.generated_jooq.tables.MdQuestionTopicElementTemplate;
import com.generated_jooq.tables.MdQuestionTopicTemplate;
import com.generated_jooq.tables.OdCommunication;
import com.generated_jooq.tables.OdConversation;
import com.generated_jooq.tables.OdConversationTopic;
import com.generated_jooq.tables.OdUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ad_users</code>.
     */
    public final AdUsers AD_USERS = AdUsers.AD_USERS;

    /**
     * The table <code>public.ch_completions</code>.
     */
    public final ChCompletions CH_COMPLETIONS = ChCompletions.CH_COMPLETIONS;

    /**
     * Шаблон за елементи към въпросна тема
     */
    public final MdQuestionTopicElementTemplate MD_QUESTION_TOPIC_ELEMENT_TEMPLATE = MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE;

    /**
     * Шаблон за въпросна тема
     */
    public final MdQuestionTopicTemplate MD_QUESTION_TOPIC_TEMPLATE = MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE;

    /**
     * Комуникация по тема в разговор
     */
    public final OdCommunication OD_COMMUNICATION = OdCommunication.OD_COMMUNICATION;

    /**
     * Разговор с потребител
     */
    public final OdConversation OD_CONVERSATION = OdConversation.OD_CONVERSATION;

    /**
     * Теми в разговори
     */
    public final OdConversationTopic OD_CONVERSATION_TOPIC = OdConversationTopic.OD_CONVERSATION_TOPIC;

    /**
     * Потребител в системата
     */
    public final OdUser OD_USER = OdUser.OD_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AdUsers.AD_USERS,
            ChCompletions.CH_COMPLETIONS,
            MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE,
            MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE,
            OdCommunication.OD_COMMUNICATION,
            OdConversation.OD_CONVERSATION,
            OdConversationTopic.OD_CONVERSATION_TOPIC,
            OdUser.OD_USER
        );
    }
}
