/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq;


import com.generated_jooq.routines.AdUserInsert;
import com.generated_jooq.routines.ChCompletionInsert;
import com.generated_jooq.routines.Getsystemmessage;
import com.generated_jooq.routines.InsertUser;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.ad_user_insert</code>
     */
    public static void adUserInsert(
          Configuration configuration
        , String pName
        , String pEmail
    ) {
        AdUserInsert p = new AdUserInsert();
        p.setPName(pName);
        p.setPEmail(pEmail);

        p.execute(configuration);
    }

    /**
     * Call <code>public.ch_completion_insert</code>
     */
    public static void chCompletionInsert(
          Configuration configuration
        , String pRequest
        , String pResponse
    ) {
        ChCompletionInsert p = new ChCompletionInsert();
        p.setPRequest(pRequest);
        p.setPResponse(pResponse);

        p.execute(configuration);
    }

    /**
     * Call <code>public.getsystemmessage</code>
     */
    public static String getsystemmessage(
          Configuration configuration
        , String secretKey
    ) {
        Getsystemmessage f = new Getsystemmessage();
        f.setSecretKey(secretKey);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.getsystemmessage</code> as a field.
     */
    public static Field<String> getsystemmessage(
          String secretKey
    ) {
        Getsystemmessage f = new Getsystemmessage();
        f.setSecretKey(secretKey);

        return f.asField();
    }

    /**
     * Get <code>public.getsystemmessage</code> as a field.
     */
    public static Field<String> getsystemmessage(
          Field<String> secretKey
    ) {
        Getsystemmessage f = new Getsystemmessage();
        f.setSecretKey(secretKey);

        return f.asField();
    }

    /**
     * Call <code>public.insert_user</code>
     */
    public static void insertUser(
          Configuration configuration
        , String pName
        , String pEmail
    ) {
        InsertUser p = new InsertUser();
        p.setPName(pName);
        p.setPEmail(pEmail);

        p.execute(configuration);
    }
}
