/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq;


import com.generated_jooq.tables.AdUsers;
import com.generated_jooq.tables.ChCompletions;
import com.generated_jooq.tables.MdQuestionTopicElementTemplate;
import com.generated_jooq.tables.MdQuestionTopicTemplate;
import com.generated_jooq.tables.OdCommunication;
import com.generated_jooq.tables.OdConversation;
import com.generated_jooq.tables.OdConversationTopic;
import com.generated_jooq.tables.OdUser;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ad_users</code>.
     */
    public static final AdUsers AD_USERS = AdUsers.AD_USERS;

    /**
     * The table <code>public.ch_completions</code>.
     */
    public static final ChCompletions CH_COMPLETIONS = ChCompletions.CH_COMPLETIONS;

    /**
     * Шаблон за елементи към въпросна тема
     */
    public static final MdQuestionTopicElementTemplate MD_QUESTION_TOPIC_ELEMENT_TEMPLATE = MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE;

    /**
     * Шаблон за въпросна тема
     */
    public static final MdQuestionTopicTemplate MD_QUESTION_TOPIC_TEMPLATE = MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE;

    /**
     * Комуникация по тема в разговор
     */
    public static final OdCommunication OD_COMMUNICATION = OdCommunication.OD_COMMUNICATION;

    /**
     * Разговор с потребител
     */
    public static final OdConversation OD_CONVERSATION = OdConversation.OD_CONVERSATION;

    /**
     * Теми в разговори
     */
    public static final OdConversationTopic OD_CONVERSATION_TOPIC = OdConversationTopic.OD_CONVERSATION_TOPIC;

    /**
     * Потребител в системата
     */
    public static final OdUser OD_USER = OdUser.OD_USER;
}
