# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: FA Dev - the-mladens-gift-finder

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'      
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: the-mladens-gift-finder # set this to your function app name on Azure
  PACKAGE_DIRECTORY: '.\backend' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # yamllint disable-line rule:truthy
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_84D4C3D5C4C540F9BEFBBE0FC5F2B94F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69ED6E8C89D6446095DBE783F68EAC51 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6D309E59AFFD4408BAF36F450FDB8600 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'the-mladens-gift-finder'
          slot-name: 'dev'
          package: '${{ env.PACKAGE_DIRECTORY }}'
          respect-pom-xml: true
          