/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.AdUsers;
import com.generated_jooq.tables.records.AdUsersRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdUsersDao extends DAOImpl<AdUsersRecord, com.generated_jooq.tables.pojos.AdUsers, Integer> {

    /**
     * Create a new AdUsersDao without any configuration
     */
    public AdUsersDao() {
        super(AdUsers.AD_USERS, com.generated_jooq.tables.pojos.AdUsers.class);
    }

    /**
     * Create a new AdUsersDao with an attached configuration
     */
    public AdUsersDao(Configuration configuration) {
        super(AdUsers.AD_USERS, com.generated_jooq.tables.pojos.AdUsers.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.AdUsers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AdUsers.AD_USERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchById(Integer... values) {
        return fetch(AdUsers.AD_USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.AdUsers fetchOneById(Integer value) {
        return fetchOne(AdUsers.AD_USERS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.AdUsers> fetchOptionalById(Integer value) {
        return fetchOptional(AdUsers.AD_USERS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(AdUsers.AD_USERS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchByName(String... values) {
        return fetch(AdUsers.AD_USERS.NAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(AdUsers.AD_USERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchByEmail(String... values) {
        return fetch(AdUsers.AD_USERS.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public com.generated_jooq.tables.pojos.AdUsers fetchOneByEmail(String value) {
        return fetchOne(AdUsers.AD_USERS.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.AdUsers> fetchOptionalByEmail(String value) {
        return fetchOptional(AdUsers.AD_USERS.EMAIL, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AdUsers.AD_USERS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.AdUsers> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(AdUsers.AD_USERS.CREATED_AT, values);
    }
}
