/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.ChCompletions;
import com.generated_jooq.tables.records.ChCompletionsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChCompletionsDao extends DAOImpl<ChCompletionsRecord, com.generated_jooq.tables.pojos.ChCompletions, Integer> {

    /**
     * Create a new ChCompletionsDao without any configuration
     */
    public ChCompletionsDao() {
        super(ChCompletions.CH_COMPLETIONS, com.generated_jooq.tables.pojos.ChCompletions.class);
    }

    /**
     * Create a new ChCompletionsDao with an attached configuration
     */
    public ChCompletionsDao(Configuration configuration) {
        super(ChCompletions.CH_COMPLETIONS, com.generated_jooq.tables.pojos.ChCompletions.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.ChCompletions object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ChCompletions.CH_COMPLETIONS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchById(Integer... values) {
        return fetch(ChCompletions.CH_COMPLETIONS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.ChCompletions fetchOneById(Integer value) {
        return fetchOne(ChCompletions.CH_COMPLETIONS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.ChCompletions> fetchOptionalById(Integer value) {
        return fetchOptional(ChCompletions.CH_COMPLETIONS.ID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ChCompletions.CH_COMPLETIONS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ChCompletions.CH_COMPLETIONS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>request BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchRangeOfRequest(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChCompletions.CH_COMPLETIONS.REQUEST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>request IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchByRequest(String... values) {
        return fetch(ChCompletions.CH_COMPLETIONS.REQUEST, values);
    }

    /**
     * Fetch records that have <code>response BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchRangeOfResponse(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChCompletions.CH_COMPLETIONS.RESPONSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>response IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.ChCompletions> fetchByResponse(String... values) {
        return fetch(ChCompletions.CH_COMPLETIONS.RESPONSE, values);
    }
}
