/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.MdQuestionTopicTemplate;
import com.generated_jooq.tables.records.MdQuestionTopicTemplateRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;


/**
 * Шаблон за въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicTemplateDao extends DAOImpl<MdQuestionTopicTemplateRecord, com.generated_jooq.tables.pojos.MdQuestionTopicTemplate, Integer> {

    /**
     * Create a new MdQuestionTopicTemplateDao without any configuration
     */
    public MdQuestionTopicTemplateDao() {
        super(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE, com.generated_jooq.tables.pojos.MdQuestionTopicTemplate.class);
    }

    /**
     * Create a new MdQuestionTopicTemplateDao with an attached configuration
     */
    public MdQuestionTopicTemplateDao(Configuration configuration) {
        super(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE, com.generated_jooq.tables.pojos.MdQuestionTopicTemplate.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.MdQuestionTopicTemplate object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchById(Integer... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.MdQuestionTopicTemplate fetchOneById(Integer value) {
        return fetchOne(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchOptionalById(Integer value) {
        return fetchOptional(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.ID, value);
    }

    /**
     * Fetch records that have <code>seq_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfSeqNo(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SEQ_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>seq_no IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchBySeqNo(Integer... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SEQ_NO, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchByName(String... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.NAME, values);
    }

    /**
     * Fetch records that have <code>system_question BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfSystemQuestion(String lowerInclusive, String upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_QUESTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>system_question IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchBySystemQuestion(String... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_QUESTION, values);
    }

    /**
     * Fetch records that have <code>system_prompt BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfSystemPrompt(String lowerInclusive, String upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_PROMPT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>system_prompt IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchBySystemPrompt(String... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_PROMPT, values);
    }

    /**
     * Fetch records that have <code>system_check_prompt BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfSystemCheckPrompt(String lowerInclusive, String upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_CHECK_PROMPT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>system_check_prompt IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchBySystemCheckPrompt(String... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.SYSTEM_CHECK_PROMPT, values);
    }

    /**
     * Fetch records that have <code>confirmation_question BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfConfirmationQuestion(String lowerInclusive, String upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.CONFIRMATION_QUESTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>confirmation_question IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchByConfirmationQuestion(String... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.CONFIRMATION_QUESTION, values);
    }

    /**
     * Fetch records that have <code>response_structure BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchRangeOfResponseStructure(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.RESPONSE_STRUCTURE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>response_structure IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicTemplate> fetchByResponseStructure(JSONB... values) {
        return fetch(MdQuestionTopicTemplate.MD_QUESTION_TOPIC_TEMPLATE.RESPONSE_STRUCTURE, values);
    }
}
