/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.MdQuestionTopicElementTemplate;
import com.generated_jooq.tables.records.MdQuestionTopicElementTemplateRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Шаблон за елементи към въпросна тема
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdQuestionTopicElementTemplateDao extends DAOImpl<MdQuestionTopicElementTemplateRecord, com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate, Integer> {

    /**
     * Create a new MdQuestionTopicElementTemplateDao without any configuration
     */
    public MdQuestionTopicElementTemplateDao() {
        super(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE, com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate.class);
    }

    /**
     * Create a new MdQuestionTopicElementTemplateDao with an attached
     * configuration
     */
    public MdQuestionTopicElementTemplateDao(Configuration configuration) {
        super(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE, com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchById(Integer... values) {
        return fetch(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate fetchOneById(Integer value) {
        return fetchOne(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchOptionalById(Integer value) {
        return fetchOptional(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.ID, value);
    }

    /**
     * Fetch records that have <code>md_topic_template_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchRangeOfMdTopicTemplateId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.MD_TOPIC_TEMPLATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>md_topic_template_id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchByMdTopicTemplateId(Integer... values) {
        return fetch(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.MD_TOPIC_TEMPLATE_ID, values);
    }

    /**
     * Fetch records that have <code>seq_no BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchRangeOfSeqNo(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.SEQ_NO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>seq_no IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchBySeqNo(Integer... values) {
        return fetch(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.SEQ_NO, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchByName(String... values) {
        return fetch(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.NAME, values);
    }

    /**
     * Fetch records that have <code>extraction_question BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchRangeOfExtractionQuestion(String lowerInclusive, String upperInclusive) {
        return fetchRange(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.EXTRACTION_QUESTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>extraction_question IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.MdQuestionTopicElementTemplate> fetchByExtractionQuestion(String... values) {
        return fetch(MdQuestionTopicElementTemplate.MD_QUESTION_TOPIC_ELEMENT_TEMPLATE.EXTRACTION_QUESTION, values);
    }
}
