/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.OdConversation;
import com.generated_jooq.tables.records.OdConversationRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Разговор с потребител
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversationDao extends DAOImpl<OdConversationRecord, com.generated_jooq.tables.pojos.OdConversation, Integer> {

    /**
     * Create a new OdConversationDao without any configuration
     */
    public OdConversationDao() {
        super(OdConversation.OD_CONVERSATION, com.generated_jooq.tables.pojos.OdConversation.class);
    }

    /**
     * Create a new OdConversationDao with an attached configuration
     */
    public OdConversationDao(Configuration configuration) {
        super(OdConversation.OD_CONVERSATION, com.generated_jooq.tables.pojos.OdConversation.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.OdConversation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdConversation.OD_CONVERSATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchById(Integer... values) {
        return fetch(OdConversation.OD_CONVERSATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.OdConversation fetchOneById(Integer value) {
        return fetchOne(OdConversation.OD_CONVERSATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.OdConversation> fetchOptionalById(Integer value) {
        return fetchOptional(OdConversation.OD_CONVERSATION.ID, value);
    }

    /**
     * Fetch records that have <code>od_user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchRangeOfOdUserId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdConversation.OD_CONVERSATION.OD_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>od_user_id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchByOdUserId(Integer... values) {
        return fetch(OdConversation.OD_CONVERSATION.OD_USER_ID, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdConversation.OD_CONVERSATION.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchByName(String... values) {
        return fetch(OdConversation.OD_CONVERSATION.NAME, values);
    }

    /**
     * Fetch records that have <code>started_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchRangeOfStartedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(OdConversation.OD_CONVERSATION.STARTED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>started_at IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchByStartedAt(LocalDateTime... values) {
        return fetch(OdConversation.OD_CONVERSATION.STARTED_AT, values);
    }

    /**
     * Fetch records that have <code>ended_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchRangeOfEndedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(OdConversation.OD_CONVERSATION.ENDED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ended_at IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversation> fetchByEndedAt(LocalDateTime... values) {
        return fetch(OdConversation.OD_CONVERSATION.ENDED_AT, values);
    }
}
