/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.OdConversationTopic;
import com.generated_jooq.tables.records.OdConversationTopicRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;


/**
 * Теми в разговори
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdConversationTopicDao extends DAOImpl<OdConversationTopicRecord, com.generated_jooq.tables.pojos.OdConversationTopic, Integer> {

    /**
     * Create a new OdConversationTopicDao without any configuration
     */
    public OdConversationTopicDao() {
        super(OdConversationTopic.OD_CONVERSATION_TOPIC, com.generated_jooq.tables.pojos.OdConversationTopic.class);
    }

    /**
     * Create a new OdConversationTopicDao with an attached configuration
     */
    public OdConversationTopicDao(Configuration configuration) {
        super(OdConversationTopic.OD_CONVERSATION_TOPIC, com.generated_jooq.tables.pojos.OdConversationTopic.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.OdConversationTopic object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdConversationTopic.OD_CONVERSATION_TOPIC.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchById(Integer... values) {
        return fetch(OdConversationTopic.OD_CONVERSATION_TOPIC.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.OdConversationTopic fetchOneById(Integer value) {
        return fetchOne(OdConversationTopic.OD_CONVERSATION_TOPIC.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.OdConversationTopic> fetchOptionalById(Integer value) {
        return fetchOptional(OdConversationTopic.OD_CONVERSATION_TOPIC.ID, value);
    }

    /**
     * Fetch records that have <code>od_conversation_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchRangeOfOdConversationId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdConversationTopic.OD_CONVERSATION_TOPIC.OD_CONVERSATION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>od_conversation_id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchByOdConversationId(Integer... values) {
        return fetch(OdConversationTopic.OD_CONVERSATION_TOPIC.OD_CONVERSATION_ID, values);
    }

    /**
     * Fetch records that have <code>md_topic_template_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchRangeOfMdTopicTemplateId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdConversationTopic.OD_CONVERSATION_TOPIC.MD_TOPIC_TEMPLATE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>md_topic_template_id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchByMdTopicTemplateId(Integer... values) {
        return fetch(OdConversationTopic.OD_CONVERSATION_TOPIC.MD_TOPIC_TEMPLATE_ID, values);
    }

    /**
     * Fetch records that have <code>user_response BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchRangeOfUserResponse(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdConversationTopic.OD_CONVERSATION_TOPIC.USER_RESPONSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_response IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchByUserResponse(String... values) {
        return fetch(OdConversationTopic.OD_CONVERSATION_TOPIC.USER_RESPONSE, values);
    }

    /**
     * Fetch records that have <code>structured_response BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchRangeOfStructuredResponse(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(OdConversationTopic.OD_CONVERSATION_TOPIC.STRUCTURED_RESPONSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>structured_response IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchByStructuredResponse(JSONB... values) {
        return fetch(OdConversationTopic.OD_CONVERSATION_TOPIC.STRUCTURED_RESPONSE, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdConversationTopic.OD_CONVERSATION_TOPIC.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdConversationTopic> fetchByStatus(String... values) {
        return fetch(OdConversationTopic.OD_CONVERSATION_TOPIC.STATUS, values);
    }
}
