/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.OdCommunication;
import com.generated_jooq.tables.records.OdCommunicationRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;


/**
 * Комуникация по тема в разговор
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdCommunicationDao extends DAOImpl<OdCommunicationRecord, com.generated_jooq.tables.pojos.OdCommunication, Integer> {

    /**
     * Create a new OdCommunicationDao without any configuration
     */
    public OdCommunicationDao() {
        super(OdCommunication.OD_COMMUNICATION, com.generated_jooq.tables.pojos.OdCommunication.class);
    }

    /**
     * Create a new OdCommunicationDao with an attached configuration
     */
    public OdCommunicationDao(Configuration configuration) {
        super(OdCommunication.OD_COMMUNICATION, com.generated_jooq.tables.pojos.OdCommunication.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.OdCommunication object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdCommunication.OD_COMMUNICATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchById(Integer... values) {
        return fetch(OdCommunication.OD_COMMUNICATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.OdCommunication fetchOneById(Integer value) {
        return fetchOne(OdCommunication.OD_COMMUNICATION.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.OdCommunication> fetchOptionalById(Integer value) {
        return fetchOptional(OdCommunication.OD_COMMUNICATION.ID, value);
    }

    /**
     * Fetch records that have <code>od_conversation_topic_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchRangeOfOdConversationTopicId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdCommunication.OD_COMMUNICATION.OD_CONVERSATION_TOPIC_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>od_conversation_topic_id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchByOdConversationTopicId(Integer... values) {
        return fetch(OdCommunication.OD_COMMUNICATION.OD_CONVERSATION_TOPIC_ID, values);
    }

    /**
     * Fetch records that have <code>started_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchRangeOfStartedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(OdCommunication.OD_COMMUNICATION.STARTED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>started_at IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchByStartedAt(LocalDateTime... values) {
        return fetch(OdCommunication.OD_COMMUNICATION.STARTED_AT, values);
    }

    /**
     * Fetch records that have <code>system_prompt BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchRangeOfSystemPrompt(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdCommunication.OD_COMMUNICATION.SYSTEM_PROMPT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>system_prompt IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchBySystemPrompt(String... values) {
        return fetch(OdCommunication.OD_COMMUNICATION.SYSTEM_PROMPT, values);
    }

    /**
     * Fetch records that have <code>user_response BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchRangeOfUserResponse(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdCommunication.OD_COMMUNICATION.USER_RESPONSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_response IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchByUserResponse(String... values) {
        return fetch(OdCommunication.OD_COMMUNICATION.USER_RESPONSE, values);
    }

    /**
     * Fetch records that have <code>processing_duration_ms BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchRangeOfProcessingDurationMs(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdCommunication.OD_COMMUNICATION.PROCESSING_DURATION_MS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>processing_duration_ms IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchByProcessingDurationMs(Integer... values) {
        return fetch(OdCommunication.OD_COMMUNICATION.PROCESSING_DURATION_MS, values);
    }

    /**
     * Fetch records that have <code>llm_result BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchRangeOfLlmResult(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(OdCommunication.OD_COMMUNICATION.LLM_RESULT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>llm_result IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdCommunication> fetchByLlmResult(JSONB... values) {
        return fetch(OdCommunication.OD_COMMUNICATION.LLM_RESULT, values);
    }
}
