/*
 * This file is generated by jOOQ.
 */
package com.generated_jooq.tables.daos;


import com.generated_jooq.tables.OdUser;
import com.generated_jooq.tables.records.OdUserRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Потребител в системата
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdUserDao extends DAOImpl<OdUserRecord, com.generated_jooq.tables.pojos.OdUser, Integer> {

    /**
     * Create a new OdUserDao without any configuration
     */
    public OdUserDao() {
        super(OdUser.OD_USER, com.generated_jooq.tables.pojos.OdUser.class);
    }

    /**
     * Create a new OdUserDao with an attached configuration
     */
    public OdUserDao(Configuration configuration) {
        super(OdUser.OD_USER, com.generated_jooq.tables.pojos.OdUser.class, configuration);
    }

    @Override
    public Integer getId(com.generated_jooq.tables.pojos.OdUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdUser.OD_USER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchById(Integer... values) {
        return fetch(OdUser.OD_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generated_jooq.tables.pojos.OdUser fetchOneById(Integer value) {
        return fetchOne(OdUser.OD_USER.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.OdUser> fetchOptionalById(Integer value) {
        return fetchOptional(OdUser.OD_USER.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdUser.OD_USER.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchByName(String... values) {
        return fetch(OdUser.OD_USER.NAME, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdUser.OD_USER.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchByEmail(String... values) {
        return fetch(OdUser.OD_USER.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public com.generated_jooq.tables.pojos.OdUser fetchOneByEmail(String value) {
        return fetchOne(OdUser.OD_USER.EMAIL, value);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public Optional<com.generated_jooq.tables.pojos.OdUser> fetchOptionalByEmail(String value) {
        return fetchOptional(OdUser.OD_USER.EMAIL, value);
    }

    /**
     * Fetch records that have <code>secret_key BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchRangeOfSecretKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(OdUser.OD_USER.SECRET_KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>secret_key IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchBySecretKey(String... values) {
        return fetch(OdUser.OD_USER.SECRET_KEY, values);
    }

    /**
     * Fetch records that have <code>remaining_requests BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchRangeOfRemainingRequests(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OdUser.OD_USER.REMAINING_REQUESTS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>remaining_requests IN (values)</code>
     */
    public List<com.generated_jooq.tables.pojos.OdUser> fetchByRemainingRequests(Integer... values) {
        return fetch(OdUser.OD_USER.REMAINING_REQUESTS, values);
    }
}
